### ISSUE TITLE
Avoiding to rezip chr-src/ in final steps

### ISSUE THREAD

**Issue by evelynecaestecker** [pauline-ng/SIFT4G_Create_Genomic_DB#1]
Hi,

Is it possible to avoid rezipping chr-src in the final steps?
This would speed up creating a new database, depending on the species this could be significant.

regards,
Evelyne

**Comment by pauline-ng** [comment]
Try commenting out line 70 in make-SIFT-db-all.pl

Change
`gunzip $fasta_dir`;
to
# `gunzip $fasta_dir`;

Let me know if that doesn't work.
