### ISSUE TITLE
Issues in creating a database for a new organism

### ISSUE THREAD

**Issue by linf545** [pauline-ng/SIFT4G_Create_Genomic_DB#10]
Dear SIFT 4G team

Ia trying to create a SIFT database for a plant species. Follow the instructions ( https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/blob/master/README.md), I generated the files required and started to create the database using this command :

```
perl make-SIFT-db-all.pl -config Sevir_config.txt
```
The configuration file is like this :

```
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=./Sevir
ORG=setaria_viridis
ORG_VERSION=JGI_v2.1
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=../sift4g/bin/sift4g
PROTEIN_DB=./protein_db/uniref90.fasta
COMPUTER=GIS-KATNISS


# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord
```

However, the program stuck at the "Selecting alignments with median threshold" step for more than week without giving a warning or breaking message. As shown below: 

```
converting gene format to use-able input
done converting gene format
making single records file
Possible precedence issue with control flow operator at /share/apps/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Bio/DB/IndexedBase.pm line 791.
done making single records template
making noncoding records file
Possible precedence issue with control flow operator at /share/apps/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Bio/DB/IndexedBase.pm line 791.
done making noncoding records
make the fasta sequences
Possible precedence issue with control flow operator at /share/apps/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Bio/DB/IndexedBase.pm line 791.
done making the fasta sequences
start siftsharp, getting the alignments
../sift4g/bin/sift4g -d ./protein_db/uniref90_test50000.fasta -q ./Sevir/all_prot.fasta --subst ./Sevir/subst --out ./Sevir/SIFT_predictions --sub-results 
** Checking query data and substitutions files **
* processing queries: 0.00/100.00% *
* processing queries: 0.01/100.00% *
* processing queries: 0.02/100.00% *
...
* processing queries: 99.99/100.00% *
* processing queries: 100.00/100.00% *
** Searching database for candidate sequences **
* processing database part 1 (size ~0.25 GB): 0.00/100.00% *
* processing database part 1 (size ~0.25 GB): 2.50/100.00% *
...
* processing database part 1 (size ~0.25 GB): 95.00/100.00% *
* processing database part 1 (size ~0.25 GB): 97.50/100.00% *
* processing database part 1 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
* processing database part 1 (size ~1.00 GB): 0.00/100.00% *
* processing database part 1 (size ~1.00 GB): 2.50/100.00% *
...
* processing database part 1 (size ~1.00 GB): 95.00/100.00% *
* processing database part 1 (size ~1.00 GB): 97.50/100.00% *
* processing database part 1 (size ~1.00 GB): 100.00/100.00% *
** Selecting alignments with median threshold: 2.75 **
(keep running forever)
```

I was trying to trouble shoot this by creating some test files. I truncated the ref90.fa file to a test file with only 500 lines and run the same command with it.  It can run through the program without this issue. 

```
...(same as above)
* processing queries: 100.00/100.00% *
* processing queries: 100.00/100.00% *
* processing queries: 100.00/100.00% *

done getting all the scores
populating databases
Unable to read from ./Sevir/singleRecords/scaffold_36.singleRecords_noncoding
checking the databases
zipping up ./Sevir/chr-src/*
All done!
```

Not sure why it get stuck on the original file. The memory allocated was 120G. 
Please help. Thanks.

**Comment by pauline-ng** [comment]
Hi,

A couple of questions for clarification

1) Are you creating the database from Ensembl or your own gff/gz files?

2)  You said you used this command :

```
java -jar ./SIFT4G/SIFT4G_Annotator_v2.4.jar -c -i ./Setaria_reseq_poly.vcf -d ./SIFT4G/databases/Sit_JGIv2_0_22 -r ./SIFT4G/SIFT4G_results 
```

The above command shouldn't be used to generate databases, it's either

```
perl make-SIFT-db-all.pl -config <config_file>  --ensembl_download
```

or 

```
perl make-SIFT-db-all.pl -config <config_file> 
```

Please confirm which commandline you used?

3) Please change your paths in the config file to full paths.

4) How big is your ref90 database? Truncating the ref90 to 500 lines doesn't test anything because then it's such a small database -- SIFT 4G probably isn't picking up any homologs. Can you try UniRef90 to see if that works for you 

https://www.uniprot.org/downloads 

(scroll down to UniRef90 and download)

Thanks,
Pauline

**Comment by linf545** [comment]
> Hi,
> 
> A couple of questions for clarification
> 
> 1. Are you creating the database from Ensembl or your own gff/gz files?
> 2. You said you used this command :
> 
> ```
> java -jar ./SIFT4G/SIFT4G_Annotator_v2.4.jar -c -i ./Setaria_reseq_poly.vcf -d ./SIFT4G/databases/Sit_JGIv2_0_22 -r ./SIFT4G/SIFT4G_results 
> ```
> 
> The above command shouldn't be used to generate databases, it's either
> 
> ```
> perl make-SIFT-db-all.pl -config <config_file>  --ensembl_download
> ```
> 
> or
> 
> ```
> perl make-SIFT-db-all.pl -config <config_file> 
> ```
> 
> Please confirm which commandline you used?
> 
> 1. Please change your paths in the config file to full paths.
> 2. How big is your ref90 database? Truncating the ref90 to 500 lines doesn't test anything because then it's such a small database -- SIFT 4G probably isn't picking up any homologs. Can you try UniRef90 to see if that works for you
> 
> https://www.uniprot.org/downloads
> 
> (scroll down to UniRef90 and download)
> 
> Thanks,
> Pauline


Here are the clarifications : 

1)  I created the gtf from my own gff file. 

The format for my gtf is like this:
1	protein_coding	exon	1755	2026	.	+	.	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";
1	protein_coding	exon	3016	3152	.	+	.	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";
1	protein_coding	exon	3242	3328	.	+	.	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";
1	protein_coding	exon	3430	3588	.	+	.	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";
1	protein_coding	exon	3720	4225	.	+	.	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";
1	protein_coding	CDS	1783	2026	.	+	0	transcript_id "Sevir.1G000100.1.v2.1"; gene_id "Sevir.1G000100.v2.1"; gene_name "Sevir.1G000100"; gene_biotype "protein_coding";

2)  I made a mistake when pasting the command. It should be 
`perl make-SIFT-db-all.pl -config Sevir_config.txt`

3) updated configuration file: 
```
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=/Volumes/Shared/Labs/Rhee/Private/Fan/setaria_fea/SIFT4G/scripts_to_build_SIFT_db/Sevir
ORG=setaria_viridis
ORG_VERSION=JGI_v2.1
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/Volumes/Shared/Labs/Rhee/Private/Fan/setaria_fea/SIFT4G/sift4g/bin/sift4g
PROTEIN_DB=/Volumes/Shared/Labs/Rhee/Private/Fan/setaria_fea/SIFT4G/scripts_to_build_SIFT_db/protein_db/uniref90.fasta 
COMPUTER=GIS-KATNISS

...
```
location of the configuration file: /Volumes/Shared/Labs/Rhee/Private/Fan/setaria_fea/SIFT4G/scripts_to_build_SIFT_db/Sevir_config.txt

4) the 'ref90' I mentioned is the UniRef90.fa downloaded from Uniprot


Thanks,

**Comment by pauline-ng** [comment]
When you go into the directory where everything is being created, and type 

```
more fasta/*  
```

do you see protein sequences? It should be all amino acid sequences with no stops, no X, or gaps (no  *  - X ). Protein sequences should be composed of just the 20 amino acids.

Thanks,
Pauline

**Comment by linf545** [comment]
Yes, it look right to me

::::::::::::::
fasta/Sevir.1G000100.1.v2.1.fasta
::::::::::::::
>Sevir.1G000100.1.v2.1
MALALASPMASLSFRSGRISAAAIGSVARTGRAAPVGSSAFPFLRSSFVSSSSTSSASASPASLSAAVSASLAFTFSSSFAAKTALPPNDLLRSATARQRRHLATRSSGSSPSETSTDDSQSPKQEKAPFGYTRKDVLLIGVGVTAFGVGLKYGLELVGVDPLQAGNVVQLLVVLGMTVGWISTYMFRVANKDMTYAQQLRDYEKQVME
KRLESLSEAELQALLEQVEEEKQRLPQNPEEPNAVTFKKK

::::::::::::::
fasta/Sevir.1G000200.1.v2.1.fasta
::::::::::::::
>Sevir.1G000200.1.v2.1
MEAAESKQQQSNTTSLFLCNINSFLPSLQHQLPSPLPVQGAGISRSSSTLPMEHAHGGTLCAEDQKKPLTVTSCLLPARSLRSTAAVAPAAQAQSQADGDLGIRSLSFSKILSFRMARAPSSLSTNSDNYIDQLDHHVTAAKGNSTKQEREEEKLKQVCRSQSVPASVSRFKLTKGLRRVAAEENIRVFRLRVVPLVPPEASVTAAREE
AAAAEDIAAEEAVCRICMVALSEEAVLKLECCCKGELALAHRGCAIKWFSIKGNGTCDVCSKEVLNLPVTLRRLHDHPPSIIHQAQGAQQQANADRTAATTASRYRVWHGTPILVIISMLAYFCFLEQLLVGDHGTAALAISLPFACVLGLFSSLTTTKMVSRRYVWIYSAVQFLFIVLFTHLFYRYVRMQAVIAIILSTFAGFSVAIC
TNSVLLQILKWRARHVASSTTTTTGEDGHGSREPPAADLETALPPP

::::::::::::::
fasta/Sevir.1G000200.2.v2.1.fasta
::::::::::::::
>Sevir.1G000200.2.v2.1
MEAAESKQQQSNTTSLFLCNINSFLPSLQHQLPSPLPVQGAGISRSSSTLPMEHAHGGTLCAEDQKKPLTVTSCLLPARSLRSTAAVAPAAQAQSQADGDLGIRSLSFSKILSFRMARAPSSLSTNSDNYIDQLDHHVTAAKGNSTKQEREEEKLKQVCRSQSVPASVSRFKLTKGLRRVAAEENIRVFRLRVVPLVPPEASVTAAREE
AAAAEDIAAEEAVCRICMVALSEEAVLKLECCCKGELALAHRGCAIKWFSIKGNGTCDVCSKEVLNLPVTLRRLHDHPPSIIHQAQGAQQQANADRTAATTASRYRVWHGTPILVIISMLAYFCFLEQLLVGDHGTAALAISLPFACVLGLFSSLTTTKMVSRRYVRMQAVIAIILSTFAGFSVAICTNSVLLQILKWRARHVASSTTT
TTGEDGHGSREPPAADLETALPPP

::::::::::::::
fasta/Sevir.1G000300.1.v2.1.fasta
::::::::::::::
>Sevir.1G000300.1.v2.1
MSPRSLAAVLLLLLFAAAAASPSAPATTTTTTTTGGKDEEEDLQYLIDNAGDTPASDPDGWLPDPEGEDDYGDDLFQDQDQDLDLPAHHQQIDETHVVVLTAANFSSFLAATRHVMVEFYAPWCGHCQALAPDYAAAASHLAAQHAQADVALAKVDATEDTDLAQKYDVQGFPTILFFIDGVPKDYNGARTKDAIVEWINKKLGPGVQN
ITTVDDAQRILTGDDKAVLAFLDSLSGADSDELAAASRLEDTVNFYQTSSPDVAKLFHIDPAAKRPSVVLLKKEEEKLTFFDGEFKASAIADFVSANKLPLVTTLTQETSASIFGNPIKKQILLFAVANKSSKFLPIFKEAAKSFKGKLLFVFVERDNEEVGEPVANYFGITGLETTVLAYTGNEDARKFFLDGELSLDAIKDFAESFL
EDKLTPFYKSEPVPESNDGDVKIVVGKNLDLIVLDESKDVLLEIYAPWCGHCQSLEPIYNKLAKHLRGIGSLVIAKMDGTTNEHPRAKPDGYPTILFYPAGKKSFEPITFEGDRTVVEMYKFIKKHASIPFKLKRQDSSTARTGSTQTEGVKSSGTNMKDEL

::::::::::::::
fasta/Sevir.1G000400.1.v2.1.fasta
::::::::::::::
>Sevir.1G000400.1.v2.1
MDASKARELREFVEACKKDPSLLADPNLAFFRDYLESLGAKIPTAATAKATSFDKPKKSSMDDIDDDDDDDEEEDLDMRDATPEPDELDEEIVESDLELEGDIVQSDHDDPPQKMGDPSIEVTEENRDASQEAKGKAMEAMSEGKLDDAIEHLTNAIVLNPLSAIMYGTRASVFIKMKKPAAAIRDANAALEINPDSAKGYKTRGMAYA
MLGKWEEAARDLHTASNMDYDEEINAVLKKVEPNAHKIVEHRRKYDRLKKEREEKRAERDRLRRRAEAQAAYEKAKRQEQSSSRSSGGASPRGFPGGMPGGGFPGGMPGGGFPGGMPGGGFPGGMPGGFPGGAMPGGFPGGGPGNVDMSKILNDPDLMAAFSDPEVMAALQDVMNNPANFARHQANPKVGPIIAKMMAKFSGSQ
--More--(99%)

**Comment by pauline-ng** [comment]
1) Can you confirm the first line of each fasta sequence has a ">"

Should be:
>Sevir.1G000300.1.v2.1
MSPRSLAAVLLLLLFAAAAASPSAPATTTTTTTTGGKDEEEDLQYLIDNAGDTPASDPDGWLPDPEGEDDYGDDLFQDQDQDLDLPAHHQQIDETHVVVLTAANFSSFLAATRHVMVEFYAPWCGHCQALAPDYAAAASHLAAQHAQADVALAKVDATEDTDLAQKYDVQGFPTILFFIDGVPKDYNGARTKDAIVEWINKKLGPGVQN

2) In the parent directory, there is a file called "all_prot.fasta"
It is the concatenation of all of the protein sequences and is the input file for SIFT 4G.
1. ```cp all_prot.fasta all_prot.original.fasta```
2.  open up all_prot.fasta and trim it so it's only 50,000 lines

3. run sift4g from the commandline.
../sift4g/bin/sift4g -d ./protein_db/uniref90.fasta -q ./Sevir/all_prot_50000.fasta --subst ./Sevir/subst --out ./Sevir/SIFT_predictions --sub-results 

In the above instructions I'm limiting the number of querie sequences to see if it will run.

**Comment by linf545** [comment]
confirmed each fasta sequence has a ">"

when I run the first commandline
`../sift4g/bin/sift4g -d ./protein_db/uniref90.fasta -q ./Sevir/all_prot_50000.fasta --subst `
I got this. it seem some prerequisites are missing.  
../sift4g/bin/sift4g: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../sift4g/bin/sift4g)
../sift4g/bin/sift4g: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../sift4g/bin/sift4g)

**Comment by pauline-ng** [comment]
Run using full paths

(Your first message shows that SIFT 4G is installed and  can run)

**Comment by linf545** [comment]
Here is the result. 

```
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 169 (size ~0.25 GB): 100.00/100.00% *

Using: lambda = 0.243, K = 0.024, H = 0.100
** Aligning queries with candidate sequences **
* processing database part 43 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
* processing queries: 100.00/100.00% *

** Generating SIFT predictions with sequence identity: 100.00% **
* processing queries: 100.00/100.00% *

```

**Comment by pauline-ng** [comment]
Please check there are predictions in the SIFT_predictions/ folder.

If there are, then that means SIFT 4G is properly running and there are 2 possibilities -- you're running out of RAM or one of the sequences later in all_prot.fasta is causing the problem.

1) Can you count the number of protein sequences in the file and tell me the size of the file?
```
cat all_prot.fasta | grep "\>" | wc -l
ls -lh all_prot.fasta
```
2) Let's double check there are no strange amino acids
```
cat all_prot.fasta | grep -v "\>" | grep X
cat all_prot.fasta | grep -v "\>" | grep "-"
cat all_prot.fasta | grep -v "\>" | grep "*"
```
The above commands should return nothing. (It looks at the amino acid sequences only, not the header line, and makes sure there's no weird amino acids.

**Comment by linf545** [comment]
`more SIFT_predictions/*prediction`

There are predictions 
```
::::::::::::::
SIFT_predictions/Sevir.1G000100.1.v2.1.SIFTprediction
::::::::::::::
M1V	DELETERIOUS	0.00	4.32	2	132
M1L	DELETERIOUS	0.00	4.32	2	132
M1L	DELETERIOUS	0.00	4.32	2	132
M1T	DELETERIOUS	0.00	4.32	2	132
M1K	DELETERIOUS	0.00	4.32	2	132
M1R	DELETERIOUS	0.00	4.32	2	132
M1I	DELETERIOUS	0.00	4.32	2	132
M1I	DELETERIOUS	0.00	4.32	2	132
M1I	DELETERIOUS	0.00	4.32	2	132
M1M	TOLERATED	1.00	4.32	2	132
A2P	DELETERIOUS	0.03	3.78	4	132
A2S	TOLERATED	0.51	3.78	4	132
A2T	DELETERIOUS	0.04	3.78	4	132
A2G	TOLERATED	0.07	3.78	4	132
A2V	DELETERIOUS	0.02	3.78	4	132
A2E	DELETERIOUS	0.01	3.78	4	132
A2A	TOLERATED	1.00	3.78	4	132
A2A	TOLERATED	1.00	3.78	4	132
A2A	TOLERATED	1.00	3.78	4	132
A2A	TOLERATED	1.00	3.78	4	132
L3I	TOLERATED	0.19	3.78	4	132
L3V	TOLERATED	0.18	3.78	4	132
L3F	TOLERATED	0.09	3.78	4	132
L3R	DELETERIOUS	0.03	3.78	4	132
L3P	DELETERIOUS	0.04	3.78	4	132
L3H	DELETERIOUS	0.01	3.78	4	132
L3L	TOLERATED	1.00	3.78	4	132
L3L	TOLERATED	1.00	3.78	4	132
L3L	TOLERATED	1.00	3.78	4	132
L3L	TOLERATED	1.00	3.78	4	132
A4T	TOLERATED	0.06	3.65	6	132
A4P	TOLERATED	0.29	3.65	6	132
A4S	TOLERATED	0.16	3.65	6	132
A4E	DELETERIOUS	0.04	3.65	6	132
...
--More--(1%)
```
1. 
`cat all_prot.fasta | grep ">" | wc -l`
return
'819911'
this number of protein sequences is larger than I expected (should be around 48000). I checked the file and found each entry has been duplicated for 18 times.  The redundancy may comes from previous runs I terminated. Is there way to clean up all the intermediate results from previous runs? 

`ls -lh all_prot.fasta`
return
`-rw-r--r-- 1 flin dpblabrheeaccess 333M May 30 23:39 all_prot.fasta`

2. Return nothing

**Comment by linf545** [comment]
Deleted all_prot.fasta and run the program again. Problem solved.

**Comment by pauline-ng** [comment]
Great!
