### ISSUE TITLE
Use of uninitialized value within @adj_ends in subtraction (-) at make-single-records-BIOPERL.pl line 198, <IN_TX> line 792

### ISSUE THREAD

**Issue by Arynio** [pauline-ng/SIFT4G_Create_Genomic_DB#11]
Hi, I'm trying to build a SIFT annotations database but it's proving to be a challenging endeavour. I read other issues that contained similar errors, but since they weren't exactly the same, I decided to post a new one. Sorry if it's redundant.

So this is what I'm getting:

`
converting gene format to use-able input
done converting gene format
making single records file
Possible precedence issue with control flow operator at /usr/share/perl5/Bio/DB/IndexedBase.pm line 845.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/share/perl5/Bio/DB/IndexedBase.pm line 304.
Use of uninitialized value within @adj_ends in subtraction (-) at make-single-records-BIOPERL.pl line 198, <IN_TX> line 792.
Use of uninitialized value $exon_end in numeric lt (<) at make-single-records-BIOPERL.pl line 214.
Use of uninitialized value $exon_end in subtraction (-) at make-single-records-BIOPERL.pl line 226.
Use of uninitialized value $aa in string eq at make-single-records-BIOPERL.pl line 270.
Use of uninitialized value $aa in concatenation (.) or string at make-single-records-BIOPERL.pl line 276.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Use of uninitialized value $exon_num in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Argument "" isn't numeric in addition (+) at make-single-records-BIOPERL.pl line 520.
Use of uninitialized value $coord in concatenation (.) or string at make-single-records-BIOPERL.pl line 572.
`

From then on, chunks of line 572 and line 520 errors alternate till infinity.

I triple checked that all files are in their proper place and their path well indicated in the config file.

Could you give me some guidance?

Besides this, my gtf file is lacking the start_codon and stop_codon features, but according to this open issue https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/6, the error for that should appear later on. Do you know any tool that automatically edits the annotation file to include start_codon and stop_codon features?

Thank you very much for your time and help.

**Comment by pauline-ng** [comment]
1) Did you test making databases with C. ruddi and Homo sapiens (our examples)? Did they work for you?

2) If your gtf file lacks start and stop codons, the database cannot be built.

It sounds like your gtf file is missing pertinent information. Please compare your gtf file with the examples given, and put the required annotations in (like start and stop codon information.)

**Comment by Arynio** [comment]
Thanks Pauline.

1 - I tried the Homo sapiens test and it worked.

2 - We don't have the start and stop codons for most proteins from our organism. Is there any workaround that you can think of?

Thanks.

**Comment by pauline-ng** [comment]
Hi @Arynio ,

You need the start and stop codons in order to know which part of the DNA sequence is translated to protein.  Otherwise you won't be able to build a SIFT 4G database.

 Does your gene annotation file have no UTRs?  How do you know what codes for amino acid sequence? If there are no UTRs then you can use gene start and gene end to proxy for stop and start -- you'll have to add those as additional rows.

Thanks,
Pauline

**Comment by pauline-ng** [comment]
Closing issue.

(User does not have all of the required input values.)
