### ISSUE TITLE
can't locate common-utils.pl in @INC

### ISSUE THREAD

**Issue by sloux** [pauline-ng/SIFT4G_Create_Genomic_DB#12]
I am attempting to run the homo_sapiens-test before creating my own genome files.  Even though I am running the make-SIFT-db-all.pl script within the scripts_to_build_SIFT_db directory, the script doesn't seem to be able to locate the files.  If I move the dependency scripts to another location in @INC, it runs for longer, but eventually still fails.  The error I'm getting is below:

Can't locate common-utils.pl in @INC (@INC contains: /home/slo236/perl5/lib/perl                                            5 /opt/ohpc/pub/libs/gnu8/ccs/perl/5.30.0/lib/site_perl/5.30.0/x86_64-linux-thre                                            ad-multi /opt/ohpc/pub/libs/gnu8/ccs/perl/5.30.0/lib/site_perl/5.30.0 /opt/ohpc/                                            pub/libs/gnu8/ccs/perl/5.30.0/lib/5.30.0/x86_64-linux-thread-multi /opt/ohpc/pub                                            /libs/gnu8/ccs/perl/5.30.0/lib/5.30.0) at ensembl_gene_format_to_ucsc.pl line 5.

**Comment by pauline-ng** [comment]
Hi @sloux ,

I changed the code so that common-utils.pl can be found.  Can you pull the repo and try again?

Please ignore this warning
``
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.26/DynaLoader.pm
``

(which was discussed in https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/5)

Thanks,
Pauline

**Comment by sloux** [comment]
Thanks.  It's bypassing that issue now, but I'm now getting a new error message.  

** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
[ERROR:src/chain.c:102]: chain is empty after encoding, see scorerEncode function

The same error comes up regardless of whether I'm running the Candidatus or the human test files.

**Comment by pauline-ng** [comment]
This looks like a SIFT 4G error. Can you confirm that you can run sift4g by commandline?

@rvaser maintains the SIFT 4G code; the repo is  at https://github.com/rvaser/sift4g

Can you please check the SIFT4G installation? 
1) Are you able to run the test files?
2) Is your protein database set correctly in the config file?

**Comment by sloux** [comment]
The candidatus test just finished successfully.  The problem seems to have stemmed from the fact that the protein database was gzipped.  When I unzipped the database, the code ran correctly.  

Thanks for your help.

**Comment by yayawoa** [comment]
> Hi @sloux ,
> 
> I changed the code so that common-utils.pl can be found. Can you pull the repo and try again?
> 
> Please ignore this warning `Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.26/DynaLoader.pm`
> 
> (which was discussed in #5)
> 
> Thanks, Pauline
Hi !
I have the same problem when  I  running the make-SIFT-db-all.pl script within the scripts_to_build_SIFT_db directory, error I'm getting is below:
No such file or directory at /opt/SIFT4G_Create_Genomic_DB-master/common-utils.pl line 80

I checked the path ,the common-utils.pl is in the /opt/SIFT4G_Create_Genomic_DB-master/. can you tell me how to change the code?
thanks!
