### ISSUE TITLE
How to create a database locally?

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [pauline-ng/SIFT4G_Create_Genomic_DB#14]
Hi,
I'm not sure when I support the .gtf and .fa (such as genome, pep) ,  should I have to gzip and change the name ? 
And I try to run the command, there was nothing in the fasta folder with an error.

"converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
cat: './test_files/malus/fasta/*.fasta': No such file or directory"

Thanks in advance.
Best Wishes.
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

Everything is specified in the config file, and there are examples of what file format it should be inside the config file.

I recommend you run the test examples first, so if you see if SIFT 4G is installed correctly. It will also give you experience with the config files.

Best,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,
I try to run the test examples, it works. But when I try to run with my file, there was nothing in the fasta folder. I think maybe there were something wrong in my file.
Is there something wrong in my gtf or pep.fa file ?
I just make the 'CDS' with the tag 'protein_coding'.
![image](https://user-images.githubusercontent.com/46480129/69108087-90507280-0aae-11ea-9638-63e9eb1b27ff.png)
Thanks in advance.
Best Wishes,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

In your gtf file, I don't see rows indicating stop_codon and start_codon positions.

 Please see step 2 at [https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#making-a-sift-database-from-genomic-dna-fagz-and-gene-annotation-file-gff]

Assuming it's at the CDS start and ends and you know transcript orientation, you could right a script to add those positions to the gtf file.

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

Thanks for your advice. It's a little difficult work for me.  I have to spend a long time.

Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

How did you generate this gtf file?

If the CDS positions are correct, a bioinformatician should be able to write a script for you in half a day (or less).

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

I'm not sure when I add the CDS start and ends in the gtf , shall I change the CDS length?
Like this,  CDS     25312   25566  -
               
After add the start and ends, stop_codon      25312   25314  -
                                               CDS     25315   25563  -
                                               start_codon     25564   25566 -
I'm not sure right or not?
Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

How was the file generated? Knowing the software that generated the file, they'll probably have a help file / publication / readme describing how start and stop codons were identified. If you can point me to it, I can try to take a look.

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

I just generate this file by my self.  So I'm not sure about the result.
I'll find some file describing that.

Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

What software did you use to predict the genes? I assumed you didn't manually predict the genes yourself?

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

I mean I write a script to add the start_codon and the stop_codon. I try to find some script, but could not find some software to solve this problem.

Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

What software did you use to make the initial gene file? What is the software called?

(I keep asking this question in the thread above, but I see you've never replied to this question.)

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

Sorry, I could not find some software for this function . So I just use python and write a script(.py) to change the gtf file. 

Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi Liu,

I still don't think you understand my question. How did you generate this file? 

![image](https://user-images.githubusercontent.com/10286019/69392111-e6702080-0d0f-11ea-8d31-7390ccb994bd.png)

-Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

I download the .gff3 from the GDR website and then use gffread to gtf.

Thanks,
Liu

**Comment by pauline-ng** [comment]
Hi,

I have updated the SIFT code so it no longer requires start/stop codon coordinates. You should be able to build the database now.

Thanks,
Pauline

**Comment by ggoodstudydaydayup** [comment]
Hi Pauline,

Thanks for your help and patience !

Thanks,
Liu
