### ISSUE TITLE
Run each chromosome/contig independently

### ISSUE THREAD

**Issue by jarobin** [pauline-ng/SIFT4G_Create_Genomic_DB#17]
Hi Pauline,

I am trying to create a database for a mammalian genome on RefSeq. The run time is quite long (several days), and occasionally the procedure fails due to various errors (out of memory, for instance). I am wondering if it would be okay to parallelize the database creation by running it independently for each chromosome/contig. Then, after all jobs have completed, I would keep the *.gz, *.regions, and *_SIFTDB_stats.txt from each <PARENT_DIR>/<ORG_VERSION>. Do you think this would be okay?

Thanks,
Jacqueline

**Comment by pauline-ng** [comment]
Hi Jacqueline,

I don't think we ever tried parallelizing it, but sure?  Several days to run a mammalian genome sounds about right.  

Pauline
