### ISSUE TITLE
Error to build my own database

### ISSUE THREAD

**Issue by liuqianhn** [pauline-ng/SIFT4G_Create_Genomic_DB#18]
Hi, I am using your tool to build my own databases, but I have errors below:
```
cat: /home/liuq1/mysoftwares/sift/SIFT4G_Create_Genomic_DB/sift_myDB/fasta/*.fasta: No such file or directory
```

```
** Checking query data and substitutions files **


** EXITING! No valid queries to process. **
```

When I check `fasta.log`, it shows that
```
0 out of 12 translated to sequences that start with M and end with *
```

May I know what is wrong here? Thank you.

My input is 
```
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
#MITO_GENETIC_CODE_TABLE=2
#MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=/home/liuq1/mysoftwares/sift/SIFT4G_Create_Genomic_DB/sift_myDB/
ORG=mytest
ORG_VERSION=mytest

#Running SIFT 4G
SIFT4G_PATH=/home/liuq1/mysoftwares/sift/sift4g/bin/sift4g
PROTEIN_DB=/home/liuq1/mysoftwares/sift/SIFT4G_Create_Genomic_DB/uniref90.fasta


# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

```

**Comment by pauline-ng** [comment]
Hi @liuqianhn ,

What does your gene annotation file look like?
The error says it's unable to translate the DNA and gene annotations into protein sequences.

Thanks,
Pauline

**Comment by liuqianhn** [comment]
@pauline-ng Thank you for your reply. 
I download a gff3 file from genebank and then use gffread to convert to gtf file. Anything wrong regarding this gene annotation file? Thank you.

**Comment by pauline-ng** [comment]
Your fasta files are also downloaded and in the appropriate directory?

Did you do the sample examples? The sample examples show you where files belong.

**Comment by liuqianhn** [comment]
@pauline-ng Thanks.
Yes, I downloaded both fasta file and gff3 file from a same genebank for testing.
I tried to run one test examples, but that one has downloading issues of one file from ensembl.

**Comment by liuqianhn** [comment]
@pauline-ng I checked gtf file I downloaded, and found that the file does not `exon` info, and corrected the gtf with exons and now, I can run the sift correctly.

I checked the results, and could you please help me to understand the format of the output gz file.
```
#Position       Ref_allele      New_allele      Transcript_id   Gene_id Gene_name       Region  Ref_amino_acid  New_amino_acid  Position_of_amino_acid_substitution     SIFT_score      SIFT_median_sequence_info       Num_seqs_at_position dbSNP_id
```
May I know the meaning of the columns of `SIFT_score      SIFT_median_sequence_info       Num_seqs_at_position dbSNP_id`? I do not find `Variant type` and `SIFT prediction` as described in https://sift.bii.a-star.edu.sg/sift4g/SIFT4G_codes.html. Why? Thanks.

**Comment by pauline-ng** [comment]
Hi,

I think we removed those fields because they took too much space. If you use your database with the SIFT Annotator, I believe those fields will be populated.  SIFT score < 0.05 is deleterious. > 0.05 is tolerated.

**Comment by liuqianhn** [comment]
@pauline-ng Thanks.

**Comment by mw-qggp** [comment]
Hi @pauline-ng,

I want to build my own database using SIFT4G_Create_Genomic_DB, but it is running for a very long time. The status is * processing database part 164 (size ~0.25 GB): 20.00/100.00% ** and I'm using the uniprot90 database. Do you know how many parts the uniref90 database does include?

**Comment by rvaser** [comment]
Hi @mw-qggp,
you can divide the Uniref90 size with 0.25 GB to get number of parts.

Best regards,
Robert

**Comment by mw-qggp** [comment]
@rvaser,

ah, this makes sense.
Thanks, Robert

**Comment by mw-qggp** [comment]
Hi, me again,

The job to create a database was run on 8 CPU for 300 hours but the job stopped because of the walltime limit. Is there a way to speed up the procedure and to restart the program on a certain point? Thank you very much.

* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 197 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
* processing database part 50 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
=>> PBS: job killed: walltime 1080118 exceeded limit 1080000

**Comment by pauline-ng** [comment]
That's a long time. What's the organism?

How many sequences are in $meta_hash{"PARENT_DIR"}/all_prot.fasta  ?

If you do "cat  $meta_hash{"PARENT_DIR"}/all_prot.fasta | grep ^> | wc -l"  does it give the expected number of protein sequences? If it's too big, then this indicates you ran the program more than once.

Line 104 in make-SIFT-db-all.pl appends fasta sequences  to the file all_prot.fasta  . If you run it more than once, you'll have duplicates.

**Comment by mw-qggp** [comment]
Okay, it's the expected number of proteins but I've just seen that the file includes a protein sequence per transcript and not per gene. Therefore the number of sequences is 332,894. Because of many transcripts per gene, many sequences are duplicates I guess.

**Comment by pauline-ng** [comment]
I'm not sure if I've had experience building a database with >100,000 protein sequences.

Can you split the gene file into different chromosomes and run those separately? It's inconvenient, but then you might not run into a memory problem.

**Comment by mw-qggp** [comment]
Thanks for the good proposal. Besides, there were a few amino acid sequences including X's. Therefore I removed them and split by chromosomes. Now it looks better. The status after 15 hours for one chromosome is:


** Aligning queries with candidate sequences **
* processing database part 50 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
* processing queries: 100.00/100.00% *

** Generating SIFT predictions with sequence identity: 100.00% **
* processing queries: 100.00/100.00% *

**Comment by mw-qggp** [comment]
Hi, me again.
I wanted to build a database for an other organism and I used SIFT4G like above but now the processing stops after processing database part 197 (100 %) without any error message. Any idea what could happen?

**Comment by rvaser** [comment]
Hello,
did the program stop or is it still running? The last step might take a while longer.

Best regards,
Robert

**Comment by mw-qggp** [comment]
Hi,
unfortunately the program stopped. I'm searching the error ...

Best,
Marius

**Comment by rvaser** [comment]
Can you paste here the last few lines of the log?

**Comment by mw-qggp** [comment]
Excuse me for the delay...

Sometimes it stops and after restarting the script, it finishes successfully. But in some cases it doesn't want to work. The last lines of the log are:

log-file:
Mon Sep 28 12:58:44 2020 Info 6652737.hpc-batch14;started
converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/gpfs/project/projects/qggp/src/sift4g/bin/sift4g -d /gpfs/project/projects/qggp/GP_TranscriptomicsMetabolomics_barley/data/uniref90/uniref90.fasta -q /gpfs/project/projects/qggp/Potatodenovo/experiments/deleterious_alleles/SIFT4G_chr12//all_prot.fasta --subst /gpfs/project/projects/qggp/Potatodenovo/experiments/deleterious_alleles/SIFT4G_chr12//subst --out /gpfs/project/projects/qggp/Potatodenovo/experiments/deleterious_alleles/SIFT4G_chr12//SIFT_predictions --sub-results 

error-file:
processing database part 197 (size ~0.25 GB): 100.00/100.00% *

**Comment by pauline-ng** [comment]
You wrote:

"Sometimes it stops and after restarting the script, it finishes successfully. But in some cases it doesn't want to work. The last lines of the log are:"

You're restarting the script? If you do this, you need to delete the folder and start anew.  This is because  /ine 104 in make-SIFT-db-all.pl appends fasta sequences to the file all_prot.fasta . If you run it more than once, you'll have duplicates and get the out-of-memory error I see above.

**Comment by mw-qggp** [comment]
It has worked. Thank you very much for your help
