### ISSUE TITLE
How synonymous variants are predicted to be deleterious

### ISSUE THREAD

**Issue by Kalpi-ds** [pauline-ng/SIFT4G_Create_Genomic_DB#22]
Hi @pauline-ng 
Once I run SIFT on my variant set, I see variant labelled as synonymous are predicted to be deleterious.
I understand why some amino acid changes would appear to be tolerated and others not.  But I don’t understand how SIFT predict that no amino acid change (synonymous variants) can be problematic (deleterious)
Will you please explain it to me? 

chr1 | 3159715 | G | T | ENSBTAT00000016473 | ENSBTAG00000012412 | URB1 | CDS | SYNONYMOUS | S | S | 1576 | 0.02 | 3.09 | 161 | novel | DELETERIOUS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr1 | 5561002 | C | T | ENSBTAT00000052636 | ENSBTAG00000037933 | CDS | SYNONYMOUS | R | R | 84 | 0.03 | 2.68 | 303 | novel | DELETERIOUS

**Comment by pauline-ng** [comment]
When a synonymous amino acid is predicted deleterious, this means the amino acid in the protein sequence is dissimilar to the other protein homologues in the protein alignment.

There are a few scenarios when this occurs. One possibility is there is sequencing error in the reference genome and the reference amino acid is incorrect. If it's not sequencing error, the amino acid in the protein sequence in your organism has mutated away from the norm. Then another possibility is this could indicate a pseudogene if there are lots of deleterious synonymous variants in a given gene. If it's a single amino acid change in a protein, maybe it's positive evolution, but that's probably less likely. The more likely scenarios are sequencing error in the reference genome or a pseudogene.

We actually use the % of reference amino acids damaging as a QC metric.  For the human genome, 0.1% of the reference amino acid is predicted damaging. Here's an example:
https://sift.bii.a-star.edu.sg/sift4g/public//Homo_sapiens/GRCh37.74/2_SIFTDB_stats.txt

Reference predictions % damaging: 0.1 2842/2341194

This is generated for every chromosome in the <chr>_SIFTDB_stats.txt file
