### ISSUE TITLE
Error in built my own database

### ISSUE THREAD

**Issue by sunshichao0916** [pauline-ng/SIFT4G_Create_Genomic_DB#24]
Hi, SIFT4G team 
I had a problem in building my own database using sift4g tools. When execute the perl make-SIFT-db-all.pl -config Glymax_config.txt command, there will be in parent_Dir folder generates all_ prot.fasta file, but without generated a database and no error was return. I don't know where the problem is. Hope your answers, thank you.

My input files are shown below:
1. Glymax_config.txt
GENE_DOWNLOAD_SITE=/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/Glycine_max/gene-annotation-src/Glycine_max.gene.gtf.gz
PEP_FILE=/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/Glycine_max/gene-annotation-src/soybean.pep.fa
CHR_DOWNLOAD_SITE=/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/database/Glycine_max.Glycine_max_v2.1.dna.toplevel.fa.gz

GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=11
MITO_GENETIC_CODE_TABLENAME=Plant Plastid Code

PARENT_DIR=/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/PARENT_DIR
ORG=Glycine_max
ORG_VERSION=Gma2.v1

#Running SIFT 4G
SIFT4G_PATH=/vol3/agis/wangli_group/sunshichao/miniconda3/bin/sift4g
PROTEIN_DB=/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/database/uniref90.fasta

# Sub-directories, don't need to change
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
FASTA_DIR=fasta
SUBST_DIR=subst
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords/
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

2.  */chr-src/Glycine_max.Glycine_max_v2.1.dna.toplevel.fa
![image](https://user-images.githubusercontent.com/70623629/99219631-0bf71380-2818-11eb-9d6d-df0991b590c2.png)
3. */gene-annotation-src/Glycine_max.gene.gtf.gz
![image](https://user-images.githubusercontent.com/70623629/99219703-347f0d80-2818-11eb-930e-4d749ad9d6f8.png)
4. */gene-annotation-src/soybean.pep.fa
![image](https://user-images.githubusercontent.com/70623629/99219765-5082af00-2818-11eb-8880-5d9aa6ba6208.png)

**Comment by pauline-ng** [comment]
Hi,

Can you go to:
https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#monitoring-the-database-creation-process

and run the commands above to check what's been created and what hasn't? 

That's very odd that the protein .fa file is created but the database is not.

Thanks,
Pauline

**Comment by sunshichao0916** [comment]
Hi，
I rerun the perl make-SIFT-db-all.pl -config command according to the tutorial on GitHub. The following files were generated in the PARENT_DIR folder:

1. */chr-src/directory.index.dir
*/chr-src/directory.index.pag

2. */fasta/*.fasta
![image](https://user-images.githubusercontent.com/70623629/99336176-3bf7f280-28bc-11eb-8cad-8e01905d8999.png)
3. */gene-annotation-src/noncoding.txt
![image](https://user-images.githubusercontent.com/70623629/99336330-4a460e80-28bc-11eb-9d6c-616314c51b96.png)
*/gene-annotation-src/protein_coding_genes.txt
![image](https://user-images.githubusercontent.com/70623629/99336476-5631d080-28bc-11eb-9be3-785489e4ad10.png)
4. */singleRecords/
![image](https://user-images.githubusercontent.com/70623629/99336649-634ebf80-28bc-11eb-89ce-715d071f0a48.png)
5. */subst
![image](https://user-images.githubusercontent.com/70623629/99336837-706bae80-28bc-11eb-8a11-e3e98643d10b.png)

The following files were not generated:
1. SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
2. DBSNP_DIR=dbSNP

Thank you,
Sun Shichao

**Comment by pauline-ng** [comment]
Hi Sun,

This looks correct. Just to double check, can you confirm your */singleRecords/ and */subst are not empty?

If those files are not empty, then everything looks right except for calling SIFT 4G algorithm. (The algorithm that actually makes the predictions) Can you confirm the path to the executable sift4g is correct? Also, when you run the test files, you're able to make predictions for SIFT 4G?

Thanks,
Pauline

**Comment by sunshichao0916** [comment]
Hi Pauline,

First, I confirm my */singleRecords/ and */subst are not empty. Then, I ran the test file, but failed. Finally, I checked the executable sift4g file and found that it does not work properly. So, I reinstalled SIFT4g, but the following error is displayed during make. Is there any solution?

![image](https://user-images.githubusercontent.com/70623629/99347893-2a6e1500-28d3-11eb-9818-a8f692c610ad.png)
![image](https://user-images.githubusercontent.com/70623629/99347900-3063f600-28d3-11eb-915d-be041f90070e.png)

To trouble you many times, thank you
Sun Shichao

**Comment by pauline-ng** [comment]
Hi Sun,

Robert maintains the sift4g algorithm. Please post this issue (the error you wrote just above)  on 

https://github.com/rvaser/sift4g
 
and Robert will probably be able to help.

Best,
Pauline

**Comment by rvaser** [comment]
Hi Sun,
the error indicates that your compiler does not support c++11 standard, try updating both gcc and g++ compilers.

Best regards,
Robert

**Comment by sunshichao0916** [comment]
Hi Robert,

I upgraded the software, but the database still failed to built.  The alignment fold was empty, and the log file is as follow：

![image](https://user-images.githubusercontent.com/70623629/99761032-1410c500-2b30-11eb-9b50-01c15102c035.png)

When the test file is running, it also stops running in the alignments section.

![image](https://user-images.githubusercontent.com/70623629/99761155-59cd8d80-2b30-11eb-9cec-3033074c00bd.png)

Thanks !

Best regards,
Sun Shichao

**Comment by rvaser** [comment]
What is printed after the `sift4g` command?

**Comment by sunshichao0916** [comment]
Hi Robert and Pauline  ,
No error information was displayed, but the alignment command could not be continued. After two days of troubleshooting, I still couldn't find the problem.

The last print information of nohup.out file was shown in the following figure: 

![image](https://user-images.githubusercontent.com/70623629/99893269-cd9aa200-2cb8-11eb-8080-eb239686337e.png)

Thanks.
Sun

**Comment by pauline-ng** [comment]
Hi Sun,

Can you confirm all_prot.fasta file contains protein sequences?

Also -- you could run the test files OK?

Pauline

**Comment by sunshichao0916** [comment]
Hi Pauline,

The all_prot.fasta file contains protein sequences.
![image](https://user-images.githubusercontent.com/70623629/99894188-d641a700-2cbd-11eb-8198-d601ff117742.png)

The test file cannot run normally, and it stops running in the alignments.
![image](https://user-images.githubusercontent.com/70623629/99894444-81eaf700-2cbe-11eb-83f7-15b39753e627.png)

Thanks for your answers.

Sun

**Comment by sunshichao0916** [comment]
Hi Pauline and Robert,

Thank you for your patience. Unfortunately, due to personal reasons, it is still unable to solve this problem.

Can I invite you or a member of the sift4g team to build the SIFT database  for me?

Sincerely,
Sun

**Comment by pauline-ng** [comment]
Hi Sun,

I might be able to ask a former post-doc to build it for you.  
For academia, we ask that the person who builds the SIFT database be added as an author on the paper. 
For industry, it's a service and a fee would be charged.

Thanks,
Pauline

**Comment by sunshichao0916** [comment]
Hi Pauline,

We built the SIFT database for academic purposes and agreed to add the person who builds the SIFT database as an author on the paper. How can I contact you?

Thank you Pauline.  
Sun

**Comment by pauline-ng** [comment]
@sunshichao0916 

I tried looking up your email address. Is it something like 3........33@qq.com  ?

If yes, please check your inbox and respond to me, and we  can get the ball rolling.

Thanks,
Pauline

**Comment by sunshichao0916** [comment]
Updata：First, I removed the protein sequence containing "XXX", and then divided the large file into several separate files according to the chromosome number.  When I ran the build data command again, the database was built successfully.

**Comment by dcf774967** [comment]
> Updata：First, I removed the protein sequence containing "XXX", and then divided the large file into several separate files according to the chromosome number. When I ran the build data command again, the database was built successfully.
Thanks a lot! 小姐姐

**Comment by pauline-ng** [comment]
Great, thanks for figuring it out!

**Comment by dcf774967** [comment]
> Great, thanks for figuring it out!

Hey！ pauline
It's fine when I divide the chromosomes into operation. But I don't understand the "PROTEIN_DB=". When I build a database for a species, do I have to use the proteome of this species, or is this option to select relative species of this species? 

Thank you！
dcf

**Comment by pauline-ng** [comment]
Hi Dcf,

PROTEIN_DB should be a database of protein sequences like NCB redundant, SWISS-PROT/Trembl, etc.  SIFT will search for homologous sequences from this database.

Thanks,
Pauline

**Comment by dcf774967** [comment]
> 
Hi, Pauline.I got it! Thank you very much!
