### ISSUE TITLE
I find a methods for speed the analysis in sift4g to build a new database

### ISSUE THREAD

**Issue by chaimol** [pauline-ng/SIFT4G_Create_Genomic_DB#25]
when i use sift4g to build my database , I found it is very slow in use `sift4g` predication . 
# Speed up the establishment of new databases
# we can add the threads in use sift4g. Only change file `make-SIFT-db-all.pl` line 109.just add threads before `-d`.
```
my $sift4g_command = $meta_hash{"SIFT4G_PATH"} .  " -t 24 -d " . $meta_hash{"PROTEIN_DB"} . " -q " . $meta_hash{"PARENT_DIR"} . "/all_prot.fasta --subst " .  $meta_hash{"PARENT_DIR"} . "/" . $meta_hash{"SUBST_DIR"} . " --out " .  $meta_hash{"PARENT_DIR"} . "/" . $meta_hash{"SIFT_SCORE_DIR"} . " --sub-results " ;
```
use `-t 24` can use 24 threads to analysis ,The default threads is 8.

**Comment by pauline-ng** [comment]
Thank you for the tip.
