### ISSUE TITLE
error when construct database, and sift4g

### ISSUE THREAD

**Issue by YaoyaoWugmail** [pauline-ng/SIFT4G_Create_Genomic_DB#26]
Can we not use --subst ./test_files/homo_sapiens_small/subst  and --sub-results  when construct database? 

I met an error when construct the sift database. "terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error Aborted (core dumped)"

When I run 'perl make-SIFT-db-all.pl -config test_files/homo_sapiens-test.txt', it
report "converting gene format to use-able input
done converting gene format
making single records file
Possible precedence issue with control flow operator at /usr/local/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.
done making single records template
making noncoding records file
Possible precedence issue with control flow operator at /usr/local/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.
done making noncoding records
make the fasta sequences
Possible precedence issue with control flow operator at /usr/local/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.
done making the fasta sequences
start siftsharp, getting the alignments
/workdir/yw2326/SIFT/sift4g/bin/sift4g -d /workdir/yw2326/SIFT/PROTEIN_DB/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results 
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error"

Then I go to sift4g, './bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa' it run error "** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)". 
 If  don't use subst, "./bin/sift4g -q ./test_files/query.fasta -d ./test_files/sample_protein_database.fa"  it works.
I have update the gcc to 7.3 version, it still report the error.

**Comment by pauline-ng** [comment]
Can you do the following checks described here:

https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#monitoring-the-database-creation-process

and tell me which folders have files, and which don't?

Thanks,
Pauline

**Comment by YaoyaoWugmail** [comment]
I'm using the test data,    ls -lt ./test_files/homo_sapiens_small/singleRecords/*. yes 
./test_files/homo_sapiens_small/singleRecords/21.singleRecords_noncoding
./test_files/homo_sapiens_small/singleRecords/MT.singleRecords_noncoding
./test_files/homo_sapiens_small/singleRecords/21.invalidRecords
./test_files/homo_sapiens_small/singleRecords/21.singleRecords_proteins.fa
./test_files/homo_sapiens_small/singleRecords/21.singleRecords
./test_files/homo_sapiens_small/singleRecords/MT.singleRecords_proteins.fa
./test_files/homo_sapiens_small/singleRecords/MT.invalidRecords
 ./test_files/homo_sapiens_small/singleRecords/MT.singleRecords
ls SIFT_predictions/* don't,  ls -lt ./test_files/homo_sapiens_small/singleRecords_with_scores/* don't

**Comment by YaoyaoWugmail** [comment]
And after I rm  --subst  and run '/workdir/yw2326/SIFT/sift4g/bin/sift4g -d /workdir/yw2326/SIFT/PROTEIN_DB/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --out ./test_files/homo_sapiens_small/SIFT_predictions', it still running without report error

**Comment by pauline-ng** [comment]
@rvaser 

Can you help Yaoyao here?  I think his error is with regards to sift4g algorithm. 

His error (from a few messages back):

Then I go to sift4g, './bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa' it run error "** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
what(): regex_error
Aborted (core dumped)".
If don't use subst, "./bin/sift4g -q ./test_files/query.fasta -d ./test_files/sample_protein_database.fa" it works.
I have update the gcc to 7.3 version, it still report the error.

Thanks,
Pauline

**Comment by YaoyaoWugmail** [comment]
@pauline-ng  @rvaser  After I rm  --subst and run '/workdir/yw2326/SIFT/sift4g/bin/sift4g -d /workdir/yw2326/SIFT/PROTEIN_DB/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --out ./test_files/homo_sapiens_small/SIFT_predictions', I construct the database
For the directory : ls -lt test_files/homo_sapiens_small/singleRecords 
                                         21.singleRecords_noncoding; MT.singleRecords_noncoding ; 
                                          21.invalidRecords;21.singleRecords_proteins.fa;21.singleRecords; MT.singleRecords_proteins.fa; 
                                          MT.invalidRecords; MT.singleRecords
                            ls test_files/homo_sapiens_small/fasta/* have files; ls /fasta/* don't have
                          ls -lt test_files/homo_sapiens_small/singleRecords_with_scores/* have no file

**Comment by pauline-ng** [comment]
Can you confirm, when you look at 

more  ./test_files/homo_sapiens_small/all_prot.fasta

you see protein sequences in that file?

**Comment by rvaser** [comment]
Hi @YaoyaoWugmail, can you please verify that running `gcc --version` and `g++ --version` you get the 7.3 version? Also, please run `which gcc` and `which g++`.

**Comment by YaoyaoWugmail** [comment]
> Can you confirm, when you look at
> 
> more ./test_files/homo_sapiens_small/all_prot.fasta
> 
> you see protein sequences in that file?

Yes, there were all_prot.fasta in  ./test_files/homo_sapiens_small/

**Comment by YaoyaoWugmail** [comment]
> g++ --version

Yes, when I check gcc --version and g++ --version, it returns 7.3.0. And which gcc it returns '/usr/local/gcc-7.3.0/bin/gcc', which g++ it returns,  '/usr/local/gcc-7.3.0/bin/g++' I'm sure it is 7.3 version

**Comment by pauline-ng** [comment]
What is your error when you run?

`/workdir/yw2326/SIFT/sift4g/bin/sift4g -d /workdir/yw2326/SIFT/PROTEIN_DB/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --out ./test_files/homo_sapiens_small/SIFT_predictions`

I know you gave us the error for the command
`./bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa`

but I don't know if sample_protein_database.fa is properly formatted.  It is correct to use uniref90.fasta so can you run the first command above, and let us know the error?

**Comment by YaoyaoWugmail** [comment]
I re-install sift4g, it works for the test data 'homo_sapiens_small'. But When I run my data,  converting gene format to use-able input
done converting gene format
making single records file
Possible precedence issue with control flow operator at /home/yw2326/software/miniconda3/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1399.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1651.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 1791.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 2060.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 2776.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 3866.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 3866.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 4568.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 5190.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 5190.
Use of uninitialized value $fasta_subseq in concatenation (.) or string at make-single-records-BIOPERL.pl line 210, <IN_TX> line 5190.

**Comment by pauline-ng** [comment]
Check your .gtf  / .gff format is in the correct format. You can use:

**Comment by pauline-ng** [comment]
Closing issue as sift4g was reinstalled and test databases are now being generated properly. If you still have issues, please open a new issue.
