### ISSUE TITLE
Error while creating database

### ISSUE THREAD

**Issue by ruru-adra** [pauline-ng/SIFT4G_Create_Genomic_DB#28]
Hi,

I am not sure why this problem encounter during database formatting.
Error returned "[ERROR]: missing option -q (query file)"

I follow the command line provided in the manual, which doesn't require query option (-q)
This is my command line that I used to create the genomic DB: 
perl make-SIFT-db-all.pl -config ./test_files/R498.txt 

![Uploading Screenshot from 2020-12-04 09-27-22.png…]()

The fasta, single records and subst folders are not empty.

**Comment by pauline-ng** [comment]
Can you upload the png screenshot again? I can't seem to view it.

**Comment by ruru-adra** [comment]
![error](https://user-images.githubusercontent.com/3852095/101130957-69c09380-363f-11eb-8ad2-2f183f0236e2.jpeg)
image as per attached.

**Comment by pauline-ng** [comment]
It looks like you're missing your protein database file (path should be specified after "-d")

**Comment by pauline-ng** [comment]
make sure the protein database is set in the config file.

**Comment by ruru-adra** [comment]
I included the protein database link in the config file as well as the protein seq database. I ran the command but the process seems truncated. It stopped just like that. Image as attached.
![Uploading 5B379AF0-B1FB-4679-A9C3-37FE9451995A.jpeg…]()

**Comment by pauline-ng** [comment]
This looks like it's running.
