### ISSUE TITLE
Process stop while creating the database

### ISSUE THREAD

**Issue by ruru-adra** [pauline-ng/SIFT4G_Create_Genomic_DB#30]
Hi Pauline,

![Screenshot from 2020-12-15 18-06-23](https://user-images.githubusercontent.com/3852095/102276515-e0279480-3f61-11eb-8ca3-502b13c3278e.png)

The command "perl make-SIFT-db-all.pl -config <config_file>" that I used for creating the database stopped at 75% without any warning or error.
Then I tried to run the SIFT4G command (as attached) to see whether it's work or not. However,  I got this warning "Killedessing database part I etc" and the process stopped at 72.5%.

Is that means the computer is out of memory while creating the database?
Please find attached the snapshot of command line that I used and warning.

Thanks,

**Comment by pauline-ng** [comment]
@rvaser Can you take a look at the error above? (It's coming from the sift4g command)

**Comment by rvaser** [comment]
Hi @ruru-adra,
yes, the error Killed at the beginning of the row indicates that your machine ran out of memory. How much RAM does it have?

Best regards,
Robert

**Comment by ruru-adra** [comment]
Hi @rvaser ,

128Gb RAM , only 12 chromosomes (rice genome)... i will try to change another machine.

**Comment by ruru-adra** [comment]
Hi @rvaser & @pauline-ng 

My SIFT4G database was successfully created.
Thank you for your assistance.

**Comment by pauline-ng** [comment]
Great!
