### ISSUE TITLE
file not existed

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#31]
Hi, may I ask is this file 'scripts_to_build_SIFT_db/test_files/homo_sapiens_small' functioning? Because When I click on it, it show me error 404 in the page. Thank you

**Comment by pauline-ng** [comment]
scripts_to_build_SIFT_db/test_files/homo_sapiens_small   is a directory. It isn't a webpage that can be viewed in a web browser.

**Comment by zhansia** [comment]
Ok,noted with thks

**Comment by zhansia** [comment]
Hi, wanna ask if I request u to build the database for me , usually it
takes how many day to complete ?? Thank you
