### ISSUE TITLE
Error in Annotate VCF files with the SIFT Database

### ISSUE THREAD

**Issue by sunshichao0916** [pauline-ng/SIFT4G_Create_Genomic_DB#32]
Hi pauline,
      I'm sorry to disturb you again. When I use the `java -jar <Path to SIFT4G_Annotator> -c -i <Path to input vcf file> -d <Path to SIFT4G database directory> -r <Path to your results folder> -t `command, the program runs, and the output temporary file looks right. But when the final merge, there is no result file output. Did I do something wrong? Can you give me some advice?

Thank you,
Shichao

**Comment by sunshichao0916** [comment]
The temporary files are as follow:
![image](https://user-images.githubusercontent.com/70623629/102447829-ca9e9180-406b-11eb-8cc9-665f725e2c2c.png)

**Comment by sunshichao0916** [comment]
Updata: I try to run it separately according to the chromosome number, but I still report an error. The error log is as follows:
`Start Time for SIFT4G code: Fri Dec 18 13:47:14 CST 2020

Started Running .......
Running in Multitranscripts mode

Chromosome	WithSIFT4GAnnotations	WithoutSIFT4GAnnotations	Progress
The following chromosomes (or scaffolds/contigs) are not found in the SIFT 4G database and will not be annotated:
 1
Please contact us if you have any questions.
/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/sift/SIFT4G_Create_Genomic_DB-master/soybean/DB1/Gma2.v1/ 1.regions does not exist`

The database files are as follows:
![image](https://user-images.githubusercontent.com/70623629/102451235-0e48c980-4073-11eb-8c37-2b3bee29820c.png)

1.regions
`1       27354   OUT
27355   27824   IN
27825   27925   OUT
27926   27991   IN
27992   28138   OUT
28139   28320   IN
28321   58974   OUT
58975   62045   IN
62046   62566   OUT
62567   62644   IN
62645   63065   OUT
63066   63141   IN
63142   63333   OUT
`

**Comment by pauline-ng** [comment]
Does 1.regions say:

1 27354 OUT
27355 27824 IN
27825 27925 OUT
?

Is it multiple lines or 1 big line?

**Comment by sunshichao0916** [comment]
It's multiple lines.

**Comment by pauline-ng** [comment]
``
/vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/sift/SIFT4G_Create_Genomic_DB-master/soybean/DB1/Gma2.v1/ 1.regions does not exist``

When I copy the error exactly, is that a space I see in front of "1.regions"?

Is there also a space after "newallchr.filter_SIFTpredictions_  "? 

I don't expect to see spaces in filenames or paths. Can you try and fix this?

**Comment by sunshichao0916** [comment]
Hello pauline，

I run the `java -jar /vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/SIFT4G/SIFT4G_Annotator.jar -c -i /vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/VCF/newGm01.filter.vcf -d /vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/sift/SIFT4G_Create_Genomic_DB-master/soybean/DB1/Gma2.v1/ -r /vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/sift/SIFT4G_Create_Genomic_DB-master/Results3 -t` command agin, the output files as follow, and there is no space after  "newallchr.filter_SIFTpredictions_ ".
![image](https://user-images.githubusercontent.com/70623629/102483608-f6d40580-409f-11eb-9b02-b67477f94e59.png)

I tried to find out where to remove the space before 1.regions, but failed. Where else can I make some changes to remove the space?

**Comment by pauline-ng** [comment]
Can you check your .vcf file, the first column has chromosomes. Check there's no space?

`cat  /vol3/agis/wangli_group/sunshichao/soybean/P101SC17040637-01-F004/VCF/newGm01.filter.vcf | grep -v ^# | cut -f1 | more`

Can you make sure it says:

1
1
...

etc with no space in front of the "1"?

**Comment by sunshichao0916** [comment]
Hello pauline，

Thank you very much for your patience and timely answers. I removed the first column of chromosome number before the space, the program can run successfully.

Thanks again for you kind help. 

Shichao

**Comment by pauline-ng** [comment]
Great!

**Comment by 15787833237** [comment]
I meet another problem casuing my file size is empty ??
![image](https://user-images.githubusercontent.com/71312236/146333290-015cf6b0-89e3-454e-ba59-7f6048ae12be.png)
![image](https://user-images.githubusercontent.com/71312236/146333330-5a5b8ba9-cc2d-48b8-86ef-7342000dd25c.png)
![image](https://user-images.githubusercontent.com/71312236/146333381-0760feb6-3a3d-4bd4-8b03-1fd4b7a0d835.png)
The input file for annotation has 8 columns which I write a python script to generate for my snp database

**Comment by 15787833237** [comment]
My file can generate,however,whether my opening file to many, it occurs that :java.io.FileNotFoundException: /wtmp/user026/Out/SIFT4G_Create_Genomic_DB/V2/L20_03_6_TRINITY_DN1119_c0_g1.gz (Too many open files)

**Comment by pauline-ng** [comment]
Is this a different genome  / issue?  Or same soybean genome?

**Comment by 15787833237** [comment]
I try to exclude "-t",it seems to be all right,and I get the final vcf and xlsx.It is possible my genome is generated through the Trinity pipeline,all of my reads is RNA-seq

**Comment by Jiangjiangzhang6** [comment]
-rw-r--r-- 1 zmsong LLi  15785984 Mar 19 22:07 all_SIFTPredictions_1.tsv
-rw-r--r-- 1 zmsong LLi 947863552 Mar 19 22:07 all_SIFTPredictions_1.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_2.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_2.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_3.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_3.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_4.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_4.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_5.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_5.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_6.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_6.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_7.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_7.vcf
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_8.tsv
-rw-r--r-- 1 zmsong LLi         0 Mar 19 22:07 all_SIFTPredictions_8.vc

**Comment by Jiangjiangzhang6** [comment]
1       13286   C       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       34451   C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       85896   T       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       85917   C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       86011   C       G       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       91662   A       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       91680   G       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       94280   G       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       102958  T       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       141619  C       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       147698  G       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       147753  G       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       147825  A       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       151878  C       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       151984  A       G       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       152000  T       C       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       152002  G       A       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       152054  A       G       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       152059  C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       234871  C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       235003  A       G       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       235843  C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       235864  A       G       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA
1       235909  C       T       NA      NA      NA      NA      NONCODING       NA      NA      NA      NA      NA      NA      NA      NA

**Comment by Jiangjiangzhang6** [comment]
> 1 13286 C A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 34451 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 85896 T A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 85917 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 86011 C G NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 91662 A T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 91680 G A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 94280 G A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 102958 T A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 141619 C A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 147698 G A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 147753 G A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 147825 A T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 151878 C A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 151984 A G NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 152000 T C NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 152002 G A NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 152054 A G NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 152059 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 234871 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 235003 A G NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 235843 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 235864 A G NA NA NA NA NONCODING NA NA NA NA NA NA NA NA 1 235909 C T NA NA NA NA NONCODING NA NA NA NA NA NA NA NA

I run the software ,but the result just one chromosome, and the result in chromosome1 just all the NA, what's the matter,. how could i slove the error ? thanks

**Comment by pauline-ng** [comment]
@Jiangjiangzhang6 You have submitted multiple issues in for SIFT. Please combine them into 1 and create only 1 new issue. It is hard to keep track of the problem/question you're asking.

**Comment by Jiangjiangzhang6** [comment]
thank you for your reply，I had resubmit the question on Github as one by one
Best wishes



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月20日 07:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [pauline-ng/SIFT4G_Create_Genomic_DB] Error in Annotate VCF files with the SIFT Database (#32) |

@Jiangjiangzhang6 You have submitted multiple issues in for SIFT. Please combine them into 1 and create only 1 new issue. It is hard to keep track of the problem/question you're asking.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PrincyJohnson** [comment]
Hello,

I am trying to create sift database for peas (pisum sativum) and I am getting this error. I gave the directory in the config file. Can you tell me if this is wrong?
[peas_config.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/8987211/peas_config.txt)

Thanks

<img width="277" alt="Capture" src="https://user-images.githubusercontent.com/54199923/175828214-d6ef6eff-bfa2-422b-9167-c9bace9527d8.PNG">

**Comment by pauline-ng** [comment]
@PrincyJohnson 

Please do not reopen another issue, create your own. Also, same question was submitted to [another repo  ](https://github.com/rvaser/sift4g/issues/27) -- answered and closed.
