### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#33]
Hi, pauline ng, sry for disturb u. When I run, I was getting this kind of error, can u check for me? Thank you...
Below is my error:

converting gene format to use-able input
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /home/FYPuser/perl5/lib/perl5 /usr/local/lib/perl5/site_perl/5.32.0/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.32.0 /usr/local/lib/perl5/5.32.0/x86_64-linux-thread-multi /usr/local/lib/perl5/5.32.0) at gff_gene_format_to_ucsc.pl line 4.
BEGIN failed--compilation aborted at gff_gene_format_to_ucsc.pl line 4.
done converting gene format
no DNA fasta files in ./test_files/coronavirus/chr-src

**Here is my config file:**

GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=./test_files/coronavirus
ORG=Severe Acute Respiratory Syndrome Coronavirus 2
ORG_VERSION=ASM985889v3
DBSNP_VCF_FILE=Homo_sapiens.vcf.gz

#Running SIFT 4G
SIFT4G_PATH=/bigdrive/sift4g/bin/sift4g
PROTEIN_DB=/bigdrive/SIFT_databases/uniprot_sprot.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

**Comment by pauline-ng** [comment]
This error:

`Can't locate Switch.pm in @inc (you may need to install the Switch module) `

indicates you need to install the perl module Switch.

**Comment by zhansia** [comment]
Ok, thks, I will try to install and try again tq
