### ISSUE TITLE
Error in running process

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#34]
Hi, Pauline Ng, sry to disturb u again.  The previous error d solved, now I have another kind of error. The error is listed below:

I d put the DNA fasta file inside the chr-src directory, but it still pop out the error, can u help me to check on this? tq...
Below is the error:

converting gene format to use-able input
Unable to open  for reading
done converting gene format
no DNA fasta files in ./test_files/coronavirus/chr-src

**Comment by pauline-ng** [comment]
Please follow the  examples first and make sure you can make a sample database before making your own.

**Comment by zhansia** [comment]
Ok,noted with thks

**Comment by zhansia** [comment]
Hi, pauline ng, I am trying the example now by using the local computer.
May I know the file structure inside the homosapien_small directory? Thank
you

**Comment by pauline-ng** [comment]
You don't need to know the file structure -- it will be automatically generated.

Follow the instructions on the [README]( https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#test-installation)

**Comment by zhansia** [comment]
But we need to put the gtf file inside the gene-annotation.src and genomic
Fasta file inside the chr-src right ?

**Comment by pauline-ng** [comment]
I added back the missing files. Please clone the repo again.

**Comment by zhansia** [comment]
Okk,tq very much ya

**Comment by zhansia** [comment]
Hi, can u help me to check on this two file that I send, I don know whether
it is suitable for the system to use or not...
The fasta file and another one is gtf file, thank you

**Comment by pauline-ng** [comment]
Closing because user has open up multiple issues.
