### ISSUE TITLE
Error when building the sample database

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#36]
Hi, pauline ng below is the error that I face while constructing the database, can u check for me, tq..

**Error:**
done making the fasta sequences
start siftsharp, getting the alignments
cat: './test_files/homo_sapiens_small/fasta/*.fasta': No such file or directory
/bigdrive/sift4g/bin/sift4g -d /bigdrive/SIFT_databases/uniprot_sprot.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results
Can't exec "/bigdrive/sift4g/bin/sift4g": No such file or directory at make-SIFT-db-all.pl line 114.

**Comment by pauline-ng** [comment]
Closing because user has opened up multiple issues in Github.

**Comment by zhansia** [comment]
Ok,thks, I will try
