### ISSUE TITLE
Error when run the SIFT Algorithm 

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#37]
Hi, pauline ng , I am sry, I just realise that I didn't install the sift4g algorithm file, but when I run the command 'make', it pop out the error as below:

[CP] src/select_alignments.cpp
In file included from src/select_alignments.cpp:16:0:
src/select_alignments.hpp:15:29: fatal error: swsharp/swsharp.h: No such file or directory
compilation terminated.
Makefile:39: recipe for target 'obj/select_alignments.o' failed
make: *** [obj/select_alignments.o] Error 1

**Comment by rvaser** [comment]
Hi,
did you clone the SIFT4G repository with `--recursive`? If not, run `git submodule update --init --recursive` inside SIFT4G directory and then run `make`.

Best regards,
Robert

**Comment by zhansia** [comment]
Ya, I did it and it was ok, thks
