### ISSUE TITLE
I found “SIFT_SCORE=NA”, "SIFT_MEDIAN=NA", "NUM_SEQS=NA", "SIFT_PREDICTION=NA" in my output

### ISSUE THREAD

**Issue by wangnan9394** [pauline-ng/SIFT4G_Create_Genomic_DB#38]
Hi，
  I tried to build the local database, and it showed “ALL DONE！！”. However, I tested my vcf files and found the  “SIFT_SCORE=NA”, "SIFT_MEDIAN=NA", "NUM_SEQS=NA", "SIFT_PREDICTION=NA" in my results. I don't know how to deal with it, could you give me hand?

**Comment by pauline-ng** [comment]
Are you able to build the example databases? Instructions are [here](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#test-installation)

You can check that your database was created correctly by checking the steps [[here](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#monitoring-the-database-creation-process)]

**Comment by pauline-ng** [comment]
User is able to build database successfully (  #44  )
