### ISSUE TITLE
No output after building database

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#39]
Hi, pauline ng, after I build the database, the output is empty in the output file, below is the error, can help me to check ah..

Error:
done making the fasta sequences
start siftsharp, getting the alignments
cat: './test_files/coronavirus/fasta/*.fasta': No such file or directory
/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/sift4g/bin/sift4g -d /home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/uniprot-NC_045512.2.fasta -q ./test_files/coronavirus/all_prot.fasta --subst ./test_files/coronavirus/subst --out ./test_files/coronavirus/SIFT_predictions --sub-results
** Checking query data and substitutions files **

** EXITING! No valid queries to process. **

**Comment by pauline-ng** [comment]
Are you able to build the example databases? Instructions are [here](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#test-installation)

You can check that your database was created correctly by checking the steps [[here](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#monitoring-the-database-creation-process)]

**Comment by zhansia** [comment]
Yaya, just now I build the example database, and it was ok, but it comes to
creating my own database, got problem d

**Comment by pauline-ng** [comment]
Closing because multiple issues opened by same user.
