### ISSUE TITLE
Cannot create own database 

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#40]
Hi, pauline ng, I managed to create the example database, but when it come to create my own database, it pop out this error as show in below, can u help me to check...

entered mkdir ./test_files/coronavirus/ASM985889v3
converting gene format to use-able input
Unable to open  for reading
done converting gene format
making single records file
can't open ./test_files/coronavirus/gene-annotation-src/protein_coding_genes.txt at make-single-records-BIOPERL.pl line 143.
done making single records template
making noncoding records file
can't open ./test_files/coronavirus/gene-annotation-src/noncoding.txt at make-single-records-noncoding.pl line 59.
done making noncoding records
make the fasta sequences
can't open ./test_files/coronavirus/gene-annotation-src/protein_coding_genes.txt at generate-fasta-subst-files-BIOPERL.pl line 387.
done making the fasta sequences
start siftsharp, getting the alignments
cat: './test_files/coronavirus/fasta/*.fasta': No such file or directory
/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/sift4g/bin/sift4g -d /home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/uniref90.fasta -q ./test_files/coronavirus/all_prot.fasta --subst ./test_files/coronavirus/subst --out ./test_files/coronavirus/SIFT_predictions --sub-results
** Checking query data and substitutions files **

** EXITING! No valid queries to process. **

**Comment by pauline-ng** [comment]
First 3 lines gives the error
```

converting gene format to use-able input
Unable to open for reading

```
it can't read your gene file.

**Comment by zhansia** [comment]
But I d put the Fasta file in gz format..I have tried multiple time still
cannot

**Comment by pauline-ng** [comment]
This error indicates SIFT can't read your **gene file**. It can read your fasta file.
