### ISSUE TITLE
config file checking

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#41]
Hi, below is my config file, can u check for me if got any error? tq..

GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/test_files/corona$
ORG=Severe Acute Respiratory Syndrome Coronavirus 2
ORG_VERSION=ASM985889v3
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/sift4g/bin/sift4g
PROTEIN_DB=/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/uniref90.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src

**Comment by pauline-ng** [comment]
Closing, too vague. Also, user has opened up multiple issues.
