### ISSUE TITLE
annotate file error, no output

### ISSUE THREAD

**Issue by zhansia** [pauline-ng/SIFT4G_Create_Genomic_DB#42]
Hi, pauline Ng, I have successfully run the SIFT 4G annotater, but the output file is empty, below is the command while running:
can u give me some advise on how to solved this problem? tq

 
Chromosome      WithSIFT4GAnnotations   WithoutSIFT4GAnnotations        Progress
The following chromosomes (or scaffolds/contigs) are not found in the SIFT 4G database and will not be annotated:
1
Please contact us if you have any questions.
/home/FYPuser/zhan/SIFT4G_Create_Genomic_DB-master/test_files/SARS/ASM985889v3/1.regions does not exist
1                       0                       50                      Completed : 1/1

Merging temp files....
SIFT4G Annotation completed !

**Comment by pauline-ng** [comment]
Please confirm the database has been built correctly.

Follow instructions here:
https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#check-the-database
