### ISSUE TITLE
No  SIFT_score shows in chr*.gz file

### ISSUE THREAD

**Issue by wangnan9394** [pauline-ng/SIFT4G_Create_Genomic_DB#44]
Hi,
  I use this pipeline to build my datebase, "All done!". However, when i check the chr*.gz file, I found that NA in  "SIFT_score",NA in "SIFT_median_sequence_info". could you give me a hand?
Here is the pic
![image](https://user-images.githubusercontent.com/52204680/105192210-d4d41400-5b72-11eb-9b6b-781b590cd6cb.png)

I have checked my all files, it seems all right.
Thank you so much.

**Comment by pauline-ng** [comment]
Hi,

Please confirm that you can build the test databases correctly.

After confirming that you can build the test databases correctly, run the following checks:
https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#monitoring-the-database-creation-process

Thank you,
Pauline

**Comment by wangnan9394** [comment]
Thank you!
  I tested on test datebase,when it shows "** Checking query data and substitutions files **", the error followed stilled "terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error"
So I changed the command line"my $sift4g_command = $meta_hash{"SIFT4G_PATH"} .  " -d " . $meta_hash{"PROTEIN_DB"} . " -q " . $meta_hash{"PARENT_DIR"} . "/all_prot.fasta --subst " .  $meta_hash{"PARENT_DIR"} . "/" . $meta_hash{"SUBST_DIR"} . " --out " .  $meta_hash{"PARENT_DIR"} . "/" . $meta_hash{"SIFT_SCORE_DIR"} . " --sub-results " ;"
to
"my $sift4g_command = $meta_hash{"SIFT4G_PATH"} .  " -d " . $meta_hash{"PROTEIN_DB"} . " -q " . $meta_hash{"PARENT_DIR"} . "/all_prot.fasta" . " --out " .  $meta_hash{"PARENT_DIR"} . "/" . $meta_hash{"SIFT_SCORE_DIR"} . " --sub-results " ;"  could over it. But the results as my mentioned above， the score seems NA.

**Comment by pauline-ng** [comment]
You've removed passing in the substitution file.  SIFT won't know what substitution files to predict on.

**Comment by wangnan9394** [comment]
Hi Pauline,
Thank you!  you are absolutely right. The sifgt4g wasn't work. I talked with Robert @rvaser . He told me sift4g must be work under the gcc 4.9 env. Keeping the substitution file is very important. 
I really appreciate your help and suggestions.
Bests,
Nan
