### ISSUE TITLE
problem for constructing the database of test data

### ISSUE THREAD

**Issue by yinhongwei4079** [pauline-ng/SIFT4G_Create_Genomic_DB#46]
@pauline-ng Hi, we want to build database for pig. Firstly, we download the PROTEIN_DB from https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz, we run human_samll_test. But  we can't get the database. here is the output of our progress 

converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/vol3/agis/likui_group/yinhongwei/software/miniconda/bin/sift4g -d /vol3/agis/likui_group/yinhongwei/pig/uniprot/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results

we check the dir of subst, it had results of transcipt  and it show likes
 head ENST00000342101.subst
M1V
M1L
M1L
M1T
M1K
M1R
M1I
M1I
M1I
M1M
when we checked the dir of SIFT_predictions, it was empty.
i didn't know what is the problem and could you give us some guidlines ?

**Comment by pauline-ng** [comment]
Hi,

Can you tell me what's the output when you run this command directly?

`/vol3/agis/likui_group/yinhongwei/software/miniconda/bin/sift4g -d /vol3/agis/likui_group/yinhongwei/pig/uniprot/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results`

**Comment by yinhongwei4079** [comment]
@pauline-ng we run this command directly, it shows 
 /opt/gridview//pbs/dispatcher/mom_priv/jobs/6614448.admin.SC: line 2: 21876 Illegal instruction     (core dumped) /vol3/agis/likui_group/yinhongwei/software/miniconda/bin/sift4g -d /vol3/agis/likui_group/yinhongwei/pig/uniprot/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results
could you tell me what is the problem?

**Comment by pauline-ng** [comment]
@rvaser - can you help Yin Hong Wei with this "core dumped" message from sift4g?

**Comment by rvaser** [comment]
Hello,
did you compile the sift4g code on the same machine you run it? What is your OS? Can you please run `cat /proc/cpuinfo | grep "avx"` and paste the output here? `Illegal instruction` could mean that the compiled SIMD instructions are not supported on your machine.

Best regards,
Robert

**Comment by yinhongwei4079** [comment]
@rvaser we install the sift4g with miniconda. we run the code of cat /proc/cpuinfo | grep "avx". here is its output .
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms

**Comment by rvaser** [comment]
Can you try and compile from source on your machine? Might be that the bioconda executable was compiled with AVX2 which is not supported on your machine.

**Comment by yinhongwei4079** [comment]
@rvaser @pauline-ng thanks
