### ISSUE TITLE
no data in /wtmp/user026/soft/PARENT_DIR/GRCh38.83/

### ISSUE THREAD

**Issue by 15787833237** [pauline-ng/SIFT4G_Create_Genomic_DB#47]
Hi,
When I use the command line: perl make-SIFT-db-all.pl -config /PARENT_DIR/test.txt to build my database,and then I manually run like this : sift4g -q /wtmp/user026/Transdecode_out/ref.fasta -d /PARENT_DIR/all_prot.fasta , and it run successfully. However, I don't know where the result is,so I cat /wtmp/user026/soft/PARENT_DIR/GRCh38.83/ , sadlly,there is nothing.Could help me deal with my puzzle? Thanks a lot!!!

**Comment by pauline-ng** [comment]
Can you list the folders and their contents with file sizes? 

Perhaps there are empty files, and you're not getting the appropriate error.

**Comment by 15787833237** [comment]
> Can you list the folders and their contents with file sizes?
> 
> Perhaps there are empty files, and you're not getting the appropriate error.
![image](https://user-images.githubusercontent.com/71312236/122632158-8d42bb80-d103-11eb-8dc8-1107abb2059d.png)

**Comment by 15787833237** [comment]
> Can you list the folders and their contents with file sizes?
> 
> Perhaps there are empty files, and you're not getting the appropriate error.

It is still running,and result just looks like that image,thanks!

**Comment by pauline-ng** [comment]
It's still running? Wait for it to finish running then.

Results will be in $PARENT_DIR/$ORG_VERSION  (which you set in the config input file)

**Comment by 15787833237** [comment]
> It's still running? Wait for it to finish running then.
> 
> Results will be in $PARENT_DIR/$ORG_VERSION (which you set in the config input file)
![image](https://user-images.githubusercontent.com/71312236/122633452-596b9400-d10b-11eb-87f4-f8d2542b5f5f.png)
![image](https://user-images.githubusercontent.com/71312236/122633456-66888300-d10b-11eb-9496-cb08e7c151aa.png)
![image](https://user-images.githubusercontent.com/71312236/122633464-6e482780-d10b-11eb-9672-c39aee91fad8.png)

**Comment by 15787833237** [comment]
> It's still running? Wait for it to finish running then.
> 
> Results will be in $PARENT_DIR/$ORG_VERSION (which you set in the config input file)

Yes , I check the $PARENT_DIR/$ORG_VERSION ,but there is empty,it is my mistake in someway that could't get correct result ?Thanks for help me a lot !!!

**Comment by pauline-ng** [comment]
Did you install sift4g? Please install sift4g.

It's strange that your error message says

` /wtmp/user026/soft/sift4g/bin/sift4g-t 24`

did you mean to put a space in between

` /wtmp/user026/soft/sift4g/bin/sift4g -t 24`

for the SIFT4G path in the input file? (I've never tested multithreading with sift4g, so I don't know if the -t option works).

**Comment by 15787833237** [comment]
> Did you install sift4g? Please install sift4g.
> 
> It's strange that your error message says
> 
> ` /wtmp/user026/soft/sift4g/bin/sift4g-t 24`
> 
> did you mean to put a space in between
> 
> ` /wtmp/user026/soft/sift4g/bin/sift4g -t 24`
> 
> for the SIFT4G path in the input file? (I've never tested multithreading with sift4g, so I don't know if the -t option works).

Hi ,  I have installed sift4g two days ago and I did as you told me ,it seems to work completely ,but I can't find anything in  $PARENT_DIR/$ORG_VERSION , what should I do ?? Thanks for your kindness! 
![MobaXterm_H7F1o3JiKS](https://user-images.githubusercontent.com/71312236/122645360-de2ad200-d14c-11eb-8948-198ec5b363a6.png)

**Comment by pauline-ng** [comment]
When did you make the fix? 2 days ago or just today?
(The above screenshot looks correct; the screenshot from 21 hours ago does NOT look correct).

My computer I have to wait 3 days for human genome to finish running, I don't know how fast your computer is.  So you will have to wait a few days after you've may made the correction.

**Comment by 15787833237** [comment]
> When did you make the fix? 2 days ago or just today?
> (The above screenshot looks correct; the screenshot from 21 hours ago does NOT look correct).
> 
> My computer I have to wait 3 days for human genome to finish running, I don't know how fast your computer is. So you will have to wait a few days after you've may made the correction.

It's today. I did it on Linux, maybe faster.Shall I use SIFT4G_Annotator/SIFT4G_Annotator.jar to annotator my vcf file ? I still dot'n figure out what my problem is.

**Comment by pauline-ng** [comment]
You need to wait for it to finish. It takes a few days.

**Comment by 15787833237** [comment]
> You need to wait for it to finish. It takes a few days.

Hi , I check it and the work is finished, and I don't know why it is so fast.
