### ISSUE TITLE
CHECK_GENES.LOG seems to have some error

### ISSUE THREAD

**Issue by 15787833237** [pauline-ng/SIFT4G_Create_Genomic_DB#49]
Hi, when I try to run command like : perl make-SIFT-db-all.pl -config my_config.txt

However ,when I less -S CHECK_GENES.LOG ,it shows like that

ALL     0 (0/72960)     0 (0/112430163) 0(0/0)

and I am confused which my data such as reference.fasta.gz or gtf.gz even my pep.gz could not satisfy your soft condition? Thanks for your kindness for help
[reference.fasta.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/7113294/reference.fasta.txt)
[test.gtf.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/7113295/test.gtf.txt)
[test.pep.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/7113312/test.pep.txt)

ing me !

**Comment by pauline-ng** [comment]
Fasta file should end with` .fasta`, not `.txt`
