### ISSUE TITLE
Bio::DB::IndexedBase::_strip_crnl redefined

### ISSUE THREAD

**Issue by conniecl** [pauline-ng/SIFT4G_Create_Genomic_DB#5]
Hi @pauline-ng,
While running the homo test,  I find there is a error log(repeat 3 times in whole test):
```
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /public/home/lchen/software/ActivePerl-5.18.4/site/lib/Bio/DB/IndexedBase.pm line 304.
```
I'm very confused about that problem, and cannot find a way to sovle it. Hope can get some advise form you. By the way, I stiil get some results(such as below). 
```
ll GRCh38.83/
total 225881
-rw-r--r-- 1 lt bio       230954285 Nov  1 13:48 21.gz
-rw-r--r-- 1 lt bio       117688 Nov  1 13:47 21.regions
-rw-r--r-- 1 lt bio       442 Nov  1 13:53 21_SIFTDB_stats.txt
-rw-r--r-- 1 lt bio       242 Nov  1 13:50 CHECK_GENES.LOG
-rw-r--r-- 1 lt bio       926 Nov  1 13:53 homo_sapiens-test.txt
-rw-r--r-- 1 lt bio       230186 Nov  1 13:48 MT.gz
-rw-r--r-- 1 lt bio       444 Nov  1 13:48 MT.regions
-rw-r--r-- 1 lt bio       419 Nov  1 13:53 MT_SIFTDB_stats.txt
```

And thanks in advance

**Comment by pauline-ng** [comment]
Hi Connie,

I'm on vacation right now -- I'll take a look when I get back next week.

Thanks,
Pauline

**Comment by pauline-ng** [comment]
Hi Connie,

is this problem separate from the regex_error issue you raised on rvaser/sift4g repository?

Thanks,
Pauline

**Comment by pauline-ng** [comment]
This error was observed on an Ensembl / VEP thread: https://github.com/Ensembl/ensembl-vep/issues/4

My guess is Bio::DB::IndexedBase::_strip_crnl is defined twice in Bioperl. As it's Bioperl's code, I'd be cautious about changing it -  are you able to get proteins and predictions?

**Comment by conniecl** [comment]
Hi @pauline-ng ,
Very sorry about replying so late. Hope this information is useful. The problem sepatate from the rvaser/sift4g repository, and I can get proteins and predictions.

**Comment by cjfields** [comment]
@conniecl the message is essentially harmless, but I have checked in a fix to bioperl that should address this

https://github.com/bioperl/bioperl-live/commit/c944290d7a3ace634ae1efa7828a846bae50ca06

**Comment by pauline-ng** [comment]
Closing because it's a Bioperl conflict (out of scope.)
