### ISSUE TITLE
Running Test error

### ISSUE THREAD

**Issue by 15787833237** [pauline-ng/SIFT4G_Create_Genomic_DB#50]
Hi,when I run test_files, it occurs like that :
perl make-SIFT-db-all.pl -c /scripts_to_build_SIFT_db/test_files/homo_sapiens-test.txt
entered mkdir ./test_files/homo_sapiens_small
/GRCh38.83dir ./test_files/homo_sapiens_small
converting gene format to use-able input
ls: cannot access /gene-annotation-src: No such file or directory
Unable to open  for reading
done converting gene format
/*.gz: No such file or directorysmall
DNA files do not exist or did not unzip properly

**Comment by pauline-ng** [comment]
Your path is wrong?

It's :

`perl make-SIFT-db-all.pl -c test_files/homo_sapiens-test.txt`

The config file is set relative to the repo directory, if you're not in the right directory it's going to throw errors. You can always replace it with full paths.
