### ISSUE TITLE
can't open files

### ISSUE THREAD

**Issue by dodudoduding** [pauline-ng/SIFT4G_Create_Genomic_DB#51]
I have already installed swith.pm,and put all the files in the right place,can anyone help?Thanks.

converting gene format to use-able input
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /home/jiayi/miniconda3/lib/perl5/5.32/site_perl /home/jiayi/miniconda3/lib/perl5/site_perl /home/jiayi/miniconda3/lib/perl5/5.32/vendor_perl /home/jiayi/miniconda3/lib/perl5/vendor_perl /home/jiayi/miniconda3/lib/perl5/5.32/core_perl /home/jiayi/miniconda3/lib/perl5/core_perl .) at gff_gene_format_to_ucsc.pl line 4.
BEGIN failed--compilation aborted at gff_gene_format_to_ucsc.pl line 4.
done converting gene format
making single records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at make-single-records-BIOPERL.pl line 143.
done making single records template
making noncoding records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/noncoding.txt at make-single-records-noncoding.pl line 59.
done making noncoding records
make the fasta sequences
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at generate-fasta-subst-files-BIOPERL.pl line 387.
done making the fasta sequences
start siftsharp, getting the alignments
cat: '/media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/fasta/*.fasta': No such file or directory
/media/data2/jiayi/sift4g/bin/sift4g -d /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/Kandelia_rename20210915.pro.fasta -q /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/all_prot.fasta --subst /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/subst --out /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/SIFT_predictions --sub-results
** Checking query data and substitutions files **

** EXITING! No valid queries to process. **

**Comment by pauline-ng** [comment]
Where do you have Switch installed and how did you install it?


Thanks,
Pauline

**Comment by dodudoduding** [comment]
> Where do you have Switch installed and how did you install it?
> 
> Thanks, Pauline

/usr/share/perl5/Switch.pm.I install it by sudo apt-get install libswitch-perl.
And was the file error caused by the switch?Thanks

**Comment by pauline-ng** [comment]
Try typing this in the terminal and then running SIFT in the same terminal
```

export PERLLIB="$PERLLIB:/usr/share/perl5"
export PERL5LIB="$PERL5LIB:/usr/share/perl5"
```

If it works, add the environmental variable to your .bashrc

**Comment by dodudoduding** [comment]
> 

Thanks so much,this problem is solved.But it still can't recognize my file like this:
converting gene format to use-able input
Unable to open  for reading
done converting gene format
making single records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at make-single-records-BIOPERL.pl line 143.
done making single records template
making noncoding records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/noncoding.txt at make-single-records-noncoding.pl line 59.
done making noncoding records
make the fasta sequences
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at generate-fasta-subst-files-BIOPERL.pl line 387.
done making the fasta sequences
start siftsharp, getting the alignments
cat: '/media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/fasta/*.fasta': No such file or directory
/media/data2/jiayi/sift4g/bin/sift4g -d /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/Kandelia_rename20210915.pro.fasta -q /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/all_prot.fasta --subst /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/subst --out /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/SIFT_predictions --sub-results
** Checking query data and substitutions files **


** EXITING! No valid queries to process. **

**Comment by pauline-ng** [comment]
Does it work on the test file? If it works on the test examples, check that your gff (gene file) is in the correct format.

**Comment by dodudoduding** [comment]
> Does it work on the test file? If it works on the test examples, check that your gff (gene file) is in the correct format.

Test files can work,Is it possible that the situation now is caused by the other reasons?Beacause I checked the format and didn't find problems.Thanks.

**Comment by dodudoduding** [comment]
> Does it work on the test file? If it works on the test examples, check that your gff (gene file) is in the correct format.

The test files can work,are the problems exerted by the wrong format?Are there other probabilities cause the problems such as wrong path?

**Comment by pauline-ng** [comment]
Check you have read/write permission for your folders and gff file.

**Comment by dodudoduding** [comment]
> Check you have read/write permission for your folders and gff file.
Yes I do have.Let me check the format again,thanks.

**Comment by dodudoduding** [comment]
> Check you have read/write permission for your folders and gff file.

Besides,I have another question,which file has a wrong format?Only the protein or all of them?Thanks.

converting gene_ format to use-able input
Unable to open  for reading
done converting gene format
making single records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at make-single-records-BIOPERL.pl line 143.
done making single records template
making noncoding records file
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/noncoding.txt at make-single-records-noncoding.pl line 59.
done making noncoding records
make the fasta sequences
can't open /media/data2/jiayi/sift4g/scripts_to_build_SIFT_db/test_files/kandelia_obovata/gene-annotation-src/protein_coding_genes.txt at generate-fasta-subst-files-BIOPERL.pl line 387.
done making the fasta sequences

**Comment by pauline-ng** [comment]
Probably just the gene file. Check that it's similar in format to the examples.
