### ISSUE TITLE
** Checking query data and substitutions files ** terminate called after throwing an instance of 'std::regex_error'   what():  regex_error Aborted (core dumped)

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [pauline-ng/SIFT4G_Create_Genomic_DB#52]
my gcc version 9.4 and the update the g++ complier through conda,but the error exit, how could i do for this error? thanks

**Comment by pauline-ng** [comment]
This sounds like a sift4g issue. Please submit issue to https://github.com/rvaser/sift4g
