### ISSUE TITLE
Questions regarding Query IDs construction

### ISSUE THREAD

**Issue by yaada100** [pauline-ng/SIFT4G_Create_Genomic_DB#55]
Dear Pauline and Robert, 

I hope it is alright to ask these questions on here.

I have a question regarding the output.
The code results in a folder called SIFT_predictions, with alignment fasta files. If I’ve understood it correctly those sequences are with Sw aligned, so pairwise and locally with the query sequence. The identity of the sequences are listed, but what about the query sequence? There is only the ID in the file name (i.e. : ENST000063518). 

1. Can you clarify how those ids come to be?
2. The sequences are aligned locally, so is it possible to get access to the full query sequence, just with its „ID“?
3. The SIFT.prediction files provide us with position specific sift scores for the newly constructed queries, how is this information significant to us? Can it be closed back to the original query? Or is the SIFT4g annotator the sole possibility to get position specific sift scores for the query sequence?

Thanks in advance,
Yakup

**Comment by pauline-ng** [comment]
Hi Yakup,

I'll explain the results in the context of one of the test files:
` perl make-SIFT-db-all.pl  --config test_files/candidatus_carsonella_ruddii_pv_config.txt`

Run the above command, and you'll generate a bunch of files. One example file: `SIFT_prediction/BAF35125.aligned.fasta`

1. BAF35125 is a transcript id, obtained from the gtf file in` gene-annotation-src/Candidatus_carsonella_ruddii_pv.ASM1036v1.34.gtf.gz`
2. The first sequence in the file SIFT_prediction/BAF35125.aligned.fasta is BAF35125 and it is the full query sequence.
3. You can use the SIFT prediction files if you're working in protein coordinates -- just look up the <transcript_id>.SIFTprediction file and look up the amino acid substitution for the corresponding protein.

Best,
Pauline

**Comment by yaada100** [comment]
Hey Pauline, 

first of all thank you for your fast reply.
To point 2. and 3. what i meant with query is the original query. 
So in context of candidatus I meant Candidatus_carsonella_ruddii_pv.ASM1036v1.dna.chromosome.Chromosome.fa as "Query". So can those results be closed back to this sequence.

Best, 
Yakup

**Comment by pauline-ng** [comment]
If we define the genomic sequence as "Query", then go to `candidatus_carsonella_ruddii_pv/ASM1036v1.34/Chromosome.gz`

In this file:
Column 1 is the position in the query sequence
Column 2: the reference DNA allele

 SIFT information is in other columns.

**Comment by yaada100** [comment]
Hello Pauline, 

If i have understood it correct, the queries(in SIFT_prediction folder) used in the files are acquired from the gtf file, right? 
But they do vary from the sequences found in the gtf file. It seems, like there has been a sequence which has been inserted.

1. Can you explain to me or link me to an explanation on what change is done and how these sequences are created/chosen as query?
2. Also if the change that is done is just the longest increasing subsequence algorithm, then why does the start and end seem to not change?
3. Lastly, this Query sequence is locally pairwise aligned(SW) with the collected sequences and sift scores are calculated. But is this sequence, which is found in the files(*.aligned.fasta) the whole sequence? Because the whole sequence is aligned, it seems more like a global alignment.


For example as in here(Homo sapien file):

**Found in ENST00000628202.aligned.fasta:**
MAAIPALDPEAEPSMDVILVGSSELSSSVSPGTGRDLIAYEVKANQRNIEDICICCGSLQVHTQHPLFEGGICAPCKDKFLDALFLYDDDGYQSYCSICCSGETLLICGNPDCTRCYCFECVDSLVGPGTSGKVHAMSNWVCYLCLPSSRSGLLQRRRKWRSQLKAFYDRESENPLEMFETVPVWRRQPVRVLSLFEDIKKELTSLGFLESGSDPGQLKHVVDVTDTVRKDVEEWGPFDLVYGATPPLGHTCDRPPSWYLFQFHRLLQYARPKPGSPRPFFWMFVDNLVLNKEDLDVASRFLEMEPVTIPDVHGGSLQNAVRVWSNIPAIRSRHWALVSEEELSLLAQNKQSSKLAAKWPTKLVKNCFLPLREYFKYFSTELTSSL
 length of sequences: 386


**Found in Homo_sapiens.GRCh38.pep.all.fa:**
>ENSP00000486001.1 pep:known chromosome:GRCh38:21:44246352:44261890:-1 gene:ENSG00000142182.8 transcript:ENST00000628202.2 gene_biotype:protein_coding transcript_biotype:protein_coding

MAAIPALDPEAEPSMDVILVGSSELSSSVSPGTGRDLIAYEVKANQRNIEDICICCGSLQMAAIPALDPEAEPSMDVILVGSSELSSSVSPGTGRDLIAYEVKANQRNIEDICICCGSLQVHTQHPLFEGGICAPCKDKFLDALFLYDDDGYQSYCSICCSGETLLICGNPDCTRCYCFECVDSLVGPGTSGKVHAMSNWVCYLCLPSSRSGLLQRRRKWRSQLKAFYDRESENPLEMFETVPVWRRQPVRVLSLFEDIKKELTSLGFLESGSDPGQLKHVVDVTDTVRKDVEEWGPFDLVYGATPPLGHTCDRPPSWYLFQFHRLLQYARPKPGSPRPFFWMFVDNLVLNKEDLDVASRFLEMEPVTIPDVHGGSLQNAVRVWSNIPAIRSRHWALVSEEELSLLAQNKQSSKLAAKWPTKLVKNCFLPLREYFKYFSTELTSSL
length of sequences: 446


_Insert_ : MAAIPALDPEAEPSMDVILVGSSELSSSVSPGTGRDLIAYEVKANQRNIEDICICCGSLQ
