### ISSUE TITLE
Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 446, <IN_TX> line 37345.

### ISSUE THREAD

**Issue by lizhiminlhy** [pauline-ng/SIFT4G_Create_Genomic_DB#59]
@pauline-ng
Hi Pauline，

A big log file with repetitive warnings like "Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 446, <IN_TX> line 37345." 

When I run the sample files, SIFT4G databases created correctly.

I look in the fasta directory for my file , I see protein sequences.

This is my file tree:
|-- chr-src  genomic.fa.gz
|-- gene-annotation-src  genomic.gtf.gz
|-- dbSNP  xx.vcf.gz

My config-file:
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=5
MITO_GENETIC_CODE_TABLENAME=Invertebrate Mitochondrial

PARENT_DIR=/public/home/lizhimin/biosoft/sift4g/scripts_to_build_SIFT_db/hefeishi_test/hefeishi
ORG=hefeishi
ORG_VERSION=GRCh38.83
# DBSNP_VCF_FILE=hefeishi.LDfilter-SRR-remove.vcf.gz

#Running SIFT 4G
SIFT4G_PATH=~/anaconda3/bin/sift4g
PROTEIN_DB=/public/home/lizhimin/biosoft/sift4g/scripts_to_build_SIFT_db/hefeishi_test/protein.faa

Any advice?

Thanks,
LiZhimin

**Comment by pauline-ng** [comment]
Hi Liz,

You can just ignore that warning. I ignore it myself. :)

Best,
Pauline
