### ISSUE TITLE
Issue making SIFT database from local genomic and gene annotation file (.gtf)

### ISSUE THREAD

**Issue by frankiefattorini** [pauline-ng/SIFT4G_Create_Genomic_DB#60]
Hello

I'm trying to make a SIFT database for chromosome 3 of Dictyostelium discoideum in order to analyse some VCF files of SNPs generated for certain genes among various strains. I have followed the protocol outlined for making a SIFT database with local genomic and gene attonation files (.gtf). I have installed all modules which I was prompted to install in order to run `perl make-SIFT-db-all.pl -config <config_file>`.  The script runs until the error `cat: 'test_files/output/fasta/*.fasta': No such file or directory`.  It then ends with 
`** Checking query data and substitutions files **

** EXITING! No valid queries to process. **` 
Are there any common errors I might be making?
Thank you

**Comment by pauline-ng** [comment]
Hi Frankie,

The error indicates to me that it can't take the genomic sequence and translate it into proteins (using the gtf file for protein coordinates). 

Did the test files work?
Do the chromosome names in the fasta file match the chromosome names in the gtf file?

**Comment by frankiefattorini** [comment]
Hello,

I'm running the Homo sapiens test files now and they appear to be working. I think you are right, as I was attempting to use fasta sequence for only the chromosome in which my genes of interest are located as opposed to the entire chromosome. Is it likely then that this issue will be solved if I use the entire genome sequence fasta, or if I trim the gtf file used to only include information regarding my chromosome of interest?

Thank you
Frankie
________________________________

**Comment by pauline-ng** [comment]
I think it'll be easier if you trim the gtf file to include only your chromosome of interest.

**Comment by frankiefattorini** [comment]
Hello,

I'm currently writing my master's degree dissertation, for which SIFT4G was an integral part. I'd like to cite the creator(s), and couldn't find any information on citing on the github page. How would I be able to cite them?

Thank you,
Gianfranco Fattorini
________________________________

**Comment by pauline-ng** [comment]
Hi, 

Thanks for asking about the citation.

Here's our publication:
https://pubmed.ncbi.nlm.nih.gov/26633127/

Best,
Pauline
