### ISSUE TITLE
For the annotation of Indel?

### ISSUE THREAD

**Issue by yilunhuangyue** [pauline-ng/SIFT4G_Create_Genomic_DB#67]
Hello, I have tried this tools and got teh result successfully. But I founf there was no prediction results for small any InDels. I wonder if this tool can predict the impact of Indels? Or any other recommanded tools? 

Thank you very much for any help.

**Comment by pauline-ng** [comment]
The code for SIFT indel for humans can be found [here](https://sift.bii.a-star.edu.sg/www/code.html)
