### ISSUE TITLE
The database was not created successfully by SIFT4G_Create_Genomic_DB

### ISSUE THREAD

**Issue by danrans123** [pauline-ng/SIFT4G_Create_Genomic_DB#74]
I can't successfully create the database with the test file
The error log is detailed below：
[run.sift4g.err.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/10367980/run.sift4g.err.txt)

The out log is detailed below：
[run.sift4g.out.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/10367985/run.sift4g.out.txt)

The error log is detailed below：
![image](https://user-images.githubusercontent.com/118544453/211187335-f31a024f-cebd-4de0-aa34-e55e1daa6b7a.png)

Where directory ASM1036v1.34、directory SIFT_predictions and directory singleRecords_with_scores are empty directories

**Comment by pauline-ng** [comment]
I don't see any errors. It looks like it was in the middle of running SIFT4G. Did you happen terminate the program? The database may take a few days to run depending on your hardware.

To make sure intermediate files are kept, please comment out line 157 of make-SIFT-db-all.pl

Original:
`system ("rm $rm_dir");`

New:
`#system ("rm $rm_dir");`

and  then re-run. You should see files in SIFT_predictions being generated

**Comment by pauline-ng** [comment]
Actually, looking a bit closer, I think your protein database is wrong.

You set your database to `Homo_Sapiens.GRcCh38.pep.all.fa` ?

It should be a protein database like SwissProt or Uniref90 - see [link](https://www.uniprot.org/help/downloads). SIFT needs protein homologues from all organisms, not just human.

**Comment by danrans123** [comment]
I have replaced 

> system ("rm $rm_dir"); 
with 

> #system ("rm $rm_dir");

 and Uniref90 as the protein database, but the program still terminates with an error.
The error message is as follows：
[run.sift4g.err.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/10479049/run.sift4g.err.txt)
The error message is as follows：
![image](https://user-images.githubusercontent.com/118544453/214027964-9704f6a1-30a5-41b5-bba4-046f2da59432.png)

The contents of the gene-annotation-src folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214028939-61fad375-999f-4234-b565-0e037481e8ef.png)

The contents of the chr-src folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214029069-911b589f-eb8d-48ce-902a-3a3fac87b2c1.png)

The contents of the dbSNP folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214029219-68fcd7a8-93d1-4639-b481-1886981c0e5e.png)

The contents of the singleRecords folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214029306-be4177d7-b535-43a8-92b9-8d25e9b0ab5c.png)

The contents of the fasta folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214029590-8ee3b45d-eb85-427f-82d2-1759350eecfa.png)

The contents of the subst folder are as follows：
![image](https://user-images.githubusercontent.com/118544453/214029749-6a90a231-a28f-4136-bd8c-1d8b73bb2401.png)

But my SIFT_predictions and singleRecords_with_scores folder is empty.

**Comment by pauline-ng** [comment]
Hi,

I looked at the run.sift4g.err.txt file and there's no error .

SIFT4G_PATH -d PROTEIN_DB -q all_prot_fasta  --subst subst --out SIFT_predictions --sub-results 

Can you try running SIFT4G by commandline directly. You'll have to put in SIFT4G_PATH and the PROTEIN_DB.

Files should be generated in SIFT_predictions generated.

Also, on my computer, a human database takes 3 days to complete.

**Comment by danrans123** [comment]
Hi,
The last line in my run.sift4g.err.txt file shows as blow:
![image](https://user-images.githubusercontent.com/118544453/214220109-18909002-f961-4f0d-8f11-47c3c4c9d059.png)
Is that okay?

**Comment by pauline-ng** [comment]
You are trying to run the test file? What are you using for your protein database?

**Comment by danrans123** [comment]
config file:
[homo_sapiens-test.txt](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/files/10488369/homo_sapiens-test.txt)
I debugged a few more times and it seems that the "start siftsharp, getting the alignmentsn" step starts to fail to continue，because the output log is as follows.

![image](https://user-images.githubusercontent.com/118544453/214263776-3d175834-6c63-4663-b705-0932990f8949.png)

**Comment by danrans123** [comment]
Yes, i'm trying to run the test file. uniref90.fasta.gz as uniref90.fasta.gz.

**Comment by pauline-ng** [comment]
In the commandline above, your database should be uniref90.fasta, not Homo_sapiens.GRCh38.pep.all.fa

Try uncompressing uniref90.fasta.gz  so it's uniref90.fasta

**Comment by danrans123** [comment]
After modifying as required：
![image](https://user-images.githubusercontent.com/118544453/214304112-40f574ff-926c-4e21-9a04-f48f61cbf14f.png)
What is the reason for this?

**Comment by pauline-ng** [comment]
Can you paste the entire screen, what does it say below Illegal instruction?

**Comment by pauline-ng** [comment]
Also, are you running this on a CPU or GPU, and how did you compile sift4g?

**Comment by danrans123** [comment]
The following figure shows all the commands that the program runs, referring to your "SIFT4G_PATH -d PROTEIN_DB -q all_prot_fasta --subst subst --out SIFT_predictions --sub-results"
![image](https://user-images.githubusercontent.com/118544453/214314425-7ee46c3f-e987-41a0-a3b2-aedef725210a.png)

I'm running under a linux server and automatically stopped with Illegal instruction after running two 100% processes. But I don't know what illegal instruction mean, it is not detailed.
About SIFT4G installation: download the SIFT4G source code and compile it manually.

**Comment by danrans123** [comment]
Also, 
I don't know why.
Even though I set the PROTEIN_DB to the path where uniprot_sprot.fasta is located in config .txt, the output log still shows that -d is the Homo_sapiens.GRCh38.pep.all.fa in the gene-annotation-src file。 As shown below: 
![image](https://user-images.githubusercontent.com/118544453/214318003-8588be81-b308-4ac2-8f73-69e87baf32ab.png)
![image](https://user-images.githubusercontent.com/118544453/214318114-2eed1a32-8b94-4035-8f6f-34ae906e8f7f.png)
. and Homo_sapiens.GRCh38.pep.all.fa file comes with test_files. When I manually delete this file and repeat the command and report the illegal instruction.

**Comment by pauline-ng** [comment]
You must use full paths in the config file (not relative paths).

Your server sounds like cpu, not gpu. When you compiled sift4g, you just used the command `make`?
How much memory do you have on your machine?

**Comment by danrans123** [comment]
I have used full paths in the config file and sift4g compiles successfully, as below:
![image](https://user-images.githubusercontent.com/118544453/214520768-81c1bcf8-210a-4024-9e90-6c56bc93f4ea.png)
our sever node memory is at least 122G，as below:
![image](https://user-images.githubusercontent.com/118544453/214521132-e3545cad-c251-4e32-bd81-b2abd6c42fc8.png)

**Comment by pauline-ng** [comment]
Please post this issue at  https://github.com/rvaser/sift4g

Perhaps @rvaser can help (He wrote the SIFT 4G algorithm)

**Comment by rvaser** [comment]
Can you directly connect to the computing node you are running sift4g and run `make` from there? The `illegal instruction` error usually means incompatibility between the computing and login node CPU instruction set (sift4g uses SIMD instructions in alignment).

Other approach is to replace `-march=native` to `-msse4.1` inside `sift4g/vendor/swsharp/swsharp/MakeFile`, line 22. Run `make` afterwards.

**Comment by danrans123** [comment]
hi
This issue has been resolved because the parameter --recursive was not added during the SIFT4G download process, resulting in some folders being empty.
But I ran into another problem with SIFT4G Annotator, I don't know how to compile SIFT4G Annotator on linux as below. 
![image](https://user-images.githubusercontent.com/118544453/215089333-7d81037b-c3ab-4043-88bc-3e3b8da86d85.png)
Do you have any suggestions?

**Comment by pauline-ng** [comment]
java files should run on linux directly.
