### ISSUE TITLE
I can not creat database

### ISSUE THREAD

**Issue by NiklausMikaelson12138** [pauline-ng/SIFT4G_Create_Genomic_DB#76]
Hi，while I creat a database，i recieve the massage said ‘’Unable to read from /home/zyi/program/sift/SIFT4G_Create_Genomic_DB/test_files/covid_19/singleRecords/MN908947.3.singleRecords_noncoding‘’，please how can i go through. The issue come from the script named make_regions_file.py

**Comment by NiklausMikaelson12138** [comment]
Unable to read from /home/zyi/program/sift/SIFT4G_Create_Genomic_DB/test_files/covid_19/singleRecords/MN908947.3.singleRecords_noncoding
Traceback (most recent call last):
  File "/home/zyi/program/sift/SIFT4G_Create_Genomic_DB/make_regions_file.py", line 69, in <module>
    get_regions (chrom_file, out_file)
  File "/home/zyi/program/sift/SIFT4G_Create_Genomic_DB/make_regions_file.py", line 32, in get_regions
    pos = get_pos (first_line)
  File "/home/zyi/program/sift/SIFT4G_Create_Genomic_DB/make_regions_file.py", line 8, in get_pos
    return int (fields[0])
ValueError: invalid literal for int() with base 10: ''

**Comment by pauline-ng** [comment]
I just released a [Dockerfile](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#running-the-code-with-docker) to help users  with installation problems. Please see if this helps.

**Comment by NiklausMikaelson12138** [comment]
你好，我已收到您的来信，我会尽快回复，谢谢
