### ISSUE TITLE
* processing database part 1 (size ~0.25 GB): 100.00/100.00% *

### ISSUE THREAD

**Issue by wanggshuoo** [pauline-ng/SIFT4G_Create_Genomic_DB#80]
Hi Pauline，
I have some questions about the result I got when I make the SIFT4G database. Here is the result of the Homo sapiens example.

converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/public1/home/sc60080/miniconda2/bin/sift4g -d /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/homo_sapiens_small/gene-annotation-src/Homo_sapiens.GRCh38.pep.all.fa -q /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/homo_sapiens_small/all_prot.fasta --subst /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/homo_sapiens_small/subst --out /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/homo_sapiens_small/SIFT_predictions --sub-results 
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 1 (size ~0.25 GB): 100.00/100.00% *

Is it all right? I haven't seen "All done!",so I doubt that if this is right.
And here is the result of my research object.

done making the fasta sequences
start siftsharp, getting the alignments
/public1/home/sc60080/miniconda2/bin/sift4g -d /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/Rehmannia_chingii/gene-annotation-src/N01_Chr_genome_final_gene.gff3.pep.fa -q /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/Rehmannia_chingii/all_prot.fasta --subst /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/Rehmannia_chingii/subst --out /public1/home/sc60080/sc60080/ws2/scripts_to_build_SIFT_db/test_files/Rehmannia_chingii/SIFT_predictions --sub-results 
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 1 (size ~0.25 GB): 100.00/100.00% *

It seems that I got the same result, but for my research object ,it takes about 30 minutes to making the database, it takes so short time that I can't believe it all done.

Any advice?
Thanks,
wangshuo

**Comment by pauline-ng** [comment]
If your genome is small, it will finish quickly. I don't see any errors, so this looks right.

**Comment by wanggshuoo** [comment]
Hi Pauline，
It seems there is not error, but there is nothing in my <PARENT_DIR>/<ORG_VERSION>,both homo sapiens and my research object .There is my configuration file for the example of homo sapiens.
![a5ac487492290f88cc9d4da81e394f0](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/131147542/33ae49a2-2bf8-4d59-98a1-0ec6291b18cf)



And there is my configuration file for my research object.
![23b2362d6d36b1edbd834081e49b579](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/131147542/37b50c3f-4b03-4258-bc74-a591068069da)




In the destination file, it's all empty in SIFT_alignments, singleRecords_with_scores,SIFT_predictions and<PARENT_DIR>/<ORG_VERSION>,both homo sapiens and my research object. 
![605c8b349b56b56757cbc8c3c0ff6be](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/131147542/8d40b0db-66cf-436c-a168-4ed1c91f5d59)
![9143cade0466022df904420a0318b56](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/131147542/f9e68b6a-0fc5-4612-9a6e-fec191fc6c92)

This happens when I use 
perl make-SIFT-db-all.pl -config test_files/homo_sapiens-test.txt .
I just really can't proceed it ,because I don't know what to do next. 

Thank you so much for your help.
wangshuo

**Comment by pauline-ng** [comment]
Can you check installation of SIFT4G by following these [instructions](https://github.com/rvaser/sift4g#check-installation)
