### ISSUE TITLE
regex_error when created database

### ISSUE THREAD

**Issue by daxian248** [pauline-ng/SIFT4G_Create_Genomic_DB#9]
Dear SIFT4G team

I followed the README.md to constructed the database for the test human genome in test_files, but I got an error:

converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/public/sxzhang/tool/sift4g/bin/sift4g -d /public/sxzhang/tool/SIFT4G_Create_Genomic_DB/test_files/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

I have tried to solve this problem by updating my g++ version to 6.1.0, but I still got the same error.

Thanks in advance for your advice.

**Comment by pauline-ng** [comment]
Hi,

The error seems to be happening at the sift4g step.  Can you go to @rvaser 's SIFT 4G repository https://github.com/rvaser/sift4g  , install, and run SIFT 4G?  

This repository is for making the databases and calls SIFT 4G.  Once you confirm that you can run SIFT 4G, then just replace the path in the config file.

Thanks.

**Comment by daxian248** [comment]
Hi Pauline,

It’s my fault, I logged into the wrong account. I installed the sift4g in my personal account and constructed the database with root. Now it works fine for the test data, you can close this issue.

Thanks for your help,
Xian

**Comment by pauline-ng** [comment]
Hi Xian,

Great, thanks!

Pauline
