### ISSUE TITLE
Problem with Creating Local Database

### ISSUE THREAD

**Issue by VNF1981** [pauline-ng/SIFT4G_Create_Genomic_DB#91]
Hello, 

I have successfully created local databases and annotated the whole genome sequences of more than 50 species via SIFT4G. However, I encountered the following issues with four species. 

**1)** I am getting the "Alignment score and position are not consensus" error for one species.

* skipping protein [ rna-XM_016942145.3 ]: substitution list has a position out of bounds (line: M1064I, query length = 1063) *
* skipping protein [ rna-XM_054680350.1 ]: substitution list has a position out of bounds (line: T345T, query length = 344) *
* skipping protein [ rna-XM_054681160.1 ]: substitution list has a position out of bounds (line: E1093D, query length = 1092) *
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 337 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
Alignment score and position are not consensus.7.50/100.00% *

///////////////////////////////////////////////////////////////////////////////////////

**2)** For three species, the process of creating databases breaks without any error during the alignment: 

* skipping protein [ rna-XM_016925611.2 ]: substitution list has a position out of bounds (line: S176R, query length = 175) *
* skipping protein [ rna-XM_024345334.2 ]: substitution list has a position out of bounds (line: E348E, query length = 347) *
* skipping protein [ rna-XM_054681488.1 ]: substitution list has a position out of bounds (line: Q138Q, query length = 137) *
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 337 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences ** 

And here is the content of log file:

converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments

/////////////////////////////////////////////////////////////////////////////////////////////////

Any advice on these would be highly appreciated in advance!

**Comment by pauline-ng** [comment]
Congrats on making almost 50 databases! 

If you used the gtf file to pull out the underlying DNA sequence for these transcripts, are they valid bases (A/C/G/T) or are there lots of N's?

Because SIFT is translating the DNA into amino acid sequence, and if there are N's, it won't be able to translate it into a protein (and SIFT won't work)

**Comment by VNF1981** [comment]
Hi Pauline,

Thank you for your prompt response!

There is no "N" in the genome sequence but ~12k "n". Do they cause the problem?

Also, as so many species do not yet have annotations on NCBI, I used Liftoff to create annotations for some species. The common point of these broken jobs is that they are all primates, and their annotations are created via Liftoff. However, lifted annotations worked for some other species, and I do not think that would cause the issue. 

Any advice on this is highly appreciated!

**Comment by VNF1981** [comment]
Hi Pauline,

The issue has been resolved! I'm not sure what caused it, but I adjusted the method for creating annotations for species that lack them, and now everything is working.

Thanks once again for your quick response!

**Comment by pauline-ng** [comment]
Great!
