### ISSUE TITLE
cat: '/cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/AK58V4MP/fasta/*.fasta': 没有那个文件或目录

### ISSUE THREAD

**Issue by fan040** [pauline-ng/SIFT4G_Create_Genomic_DB#93]
I have a question, how did the file in this error report get generated and what went wrong with my configuration?

(sift4G) perl make-SIFT-db-all.pl --config test_files/AK58V4MP.txt 
converting gene format to use-able input
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0 /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/5.22.0/x86_64-linux-thread-multi /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/5.22.0 .) at gff_gene_format_to_ucsc.pl line 4.
BEGIN failed--compilation aborted at gff_gene_format_to_ucsc.pl line 4.
done converting gene format
making single records file
Possible precedence issue with control flow operator at /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.

------------- EXCEPTION -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 3 is 300037501 chars.
STACK Bio::DB::IndexedBase::_check_linelength /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:744
STACK Bio::DB::Fasta::_calculate_offsets /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/Fasta.pm:175
STACK Bio::DB::IndexedBase::_index_files /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:648
STACK Bio::DB::IndexedBase::index_dir /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:446
STACK Bio::DB::IndexedBase::new /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:361
STACK main::generateOutput make-single-records-BIOPERL.pl:147
STACK toplevel make-single-records-BIOPERL.pl:105
-------------------------------------

done making single records template
making noncoding records file
Possible precedence issue with control flow operator at /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.

------------- EXCEPTION -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 3 is 300037501 chars.
STACK Bio::DB::IndexedBase::_check_linelength /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:744
STACK Bio::DB::Fasta::_calculate_offsets /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/Fasta.pm:175
STACK Bio::DB::IndexedBase::_index_files /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:648
STACK Bio::DB::IndexedBase::index_dir /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:446
STACK Bio::DB::IndexedBase::new /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:361
STACK main::generateOutput make-single-records-noncoding.pl:62
STACK toplevel make-single-records-noncoding.pl:51
-------------------------------------

done making noncoding records
make the fasta sequences
Possible precedence issue with control flow operator at /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.

------------- EXCEPTION -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 3 is 300037501 chars.
STACK Bio::DB::IndexedBase::_check_linelength /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:744
STACK Bio::DB::Fasta::_calculate_offsets /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/Fasta.pm:175
STACK Bio::DB::IndexedBase::_index_files /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:648
STACK Bio::DB::IndexedBase::index_dir /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:446
STACK Bio::DB::IndexedBase::new /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm:361
STACK main::generateOutput generate-fasta-subst-files-BIOPERL.pl:374
STACK toplevel generate-fasta-subst-files-BIOPERL.pl:178
-------------------------------------

done making the fasta sequences
start siftsharp, getting the alignments
cat: '/cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/AK58V4MP/fasta/*.fasta': 没有那个文件或目录
/cluster/home/fanrong/.conda/envs/sift4G/bin/sift4g -d /cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/uniref90.fasta -q /cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/AK58V4MP/all_prot.fasta --subst /cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/AK58V4MP/subst --out /cluster/home/fanrong/perl5/scripts_to_build_SIFT_db/test_files/AK58V4MP/SIFT_predictions --sub-results 
** Checking query data and substitutions files **

**Comment by pauline-ng** [comment]
1. Install switch for perl 
`Can't locate Switch.pm in @inc (you may need to install the Switch module`

2. Is your fasta file in the typical format with 60 DNA bases per line? If it's one long string, please break it up.

**Comment by fan040** [comment]
Thank you for your reply. I have installed switch.pm for many times, but it sometimes reports such errors, I would like to ask why? My fasta file, shown here, is 60 bases.
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/000af34b-f83a-4cca-bc13-0e0e44fe8201)

**Comment by pauline-ng** [comment]
- Is Switch in any of your @inc paths ( /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/site_perl/5.22.0 /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/5.22.0/x86_64-linux-thread-multi /cluster/home/fanrong/.conda/envs/sift4G/lib/perl5/5.22.0   )?

- Did the test files work for you? I'm seeing Chinese characters in the error messages -- SIFT has not been tested for other languages, so that may be throwing it off.

**Comment by fan040** [comment]
Thank you for your reply.
1.I found that there was no switch in these folders. I used the conda method to install the switch before, and the installation was successful. May I ask whether this installation is invalid? How do I install it?
![ad8287267cebe8b3a56a9294796436b](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/9f5a2287-de5c-47ca-acf3-927317c5a80b)
2.For the test file, I don't know how to solve this problem
![9fc3d90963e1f9187c28122905e7be5](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/aa1f9552-32c9-41a6-827d-9ca70e2adf49)

**Comment by pauline-ng** [comment]
You need to change the config file to your paths. I see my name in  the path `/home/pauline` which means the config file hasn't been changed to reflect your system.

**Comment by fan040** [comment]
Thank you for your reply. I said to listen to your suggestions to modify, see the running result is what.

**Comment by fan040** [comment]
I tried to run the test file and it is OK to create, the following is a picture of it.
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/586fc7e1-7456-4650-812f-aac88587c5d2)
But I can't build my own database and I'd like to ask why.
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/d13497b7-0192-46dd-bd33-b6600981684e)
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/3db552bc-f714-4765-bf6f-e6aef467faba)

**Comment by pauline-ng** [comment]
It still says Switch isn't installed.Maybe you should try the [Dockerfile](https://sift.bii.a-star.edu.sg/sift4g/AnnotateVariants.html)

**Comment by fan040** [comment]
Thank you very much for your reply. There is only apptainer in my system, so docker cannot be run. Is my test file successfully run? It doesn't seem to have this module installed either.

**Comment by pauline-ng** [comment]
[Read this](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB?tab=readme-ov-file#creating-your-own-database) to see if your database is made correctly.

**Comment by fan040** [comment]
Thank you for your reply. I would like you to have a look at my configuration process. I did not find anything wrong. I hope to get your help.
![Snipaste_2024-04-26_08-48-15](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/b93d51db-ebd5-4253-a097-7e44b6ddf21b)
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/462a3df8-045f-41fa-abf6-40619a17ac35)
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/f44baae6-71c2-4b04-b09d-e6c82a4fd256)

**Comment by pauline-ng** [comment]
It's not working. You have to install Switch.pm correctly

**Comment by fan040** [comment]
Thanks for your reply, I will try to install it again.

**Comment by fan040** [comment]
I installed the module, but still reported an error, I want to ask the reason, I am not familiar with programming, hope you can help me.
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/d7fd6f16-e067-4691-b4b2-411e75d5aba3)
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/e9b27375-1989-4240-bc04-90d19db32f97)

**Comment by fan040** [comment]
![image](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/assets/166574153/71f59354-a1e6-4f3a-877b-6ac960469dc1)
